using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace GarageAPI.Migrations
{
    /// <inheritdoc />
    public partial class InitialMigration : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "CarEngineType",
                columns: table => new
                {
                    ID = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    EngineType = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CarEngineType", x => x.ID);
                });

            migrationBuilder.CreateTable(
                name: "CarManufacturer",
                columns: table => new
                {
                    ID = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    ManufacturerName = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CarManufacturer", x => x.ID);
                });

            migrationBuilder.CreateTable(
                name: "CarModels",
                columns: table => new
                {
                    ID = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    ModelName = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CarModels", x => x.ID);
                });

            migrationBuilder.CreateTable(
                name: "CarModelYear",
                columns: table => new
                {
                    ID = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Description = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CarModelYear", x => x.ID);
                });

            migrationBuilder.CreateTable(
                name: "EngineerSpeciality",
                columns: table => new
                {
                    ID = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Speciality = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_EngineerSpeciality", x => x.ID);
                });

            //migrationBuilder.CreateTable(
            //    name: "Output",
            //    columns: table => new
            //    {
            //        id = table.Column<long>(type: "bigint", nullable: false)
            //            .Annotation("SqlServer:Identity", "1, 1"),
            //        UserID = table.Column<long>(type: "bigint", nullable: false),
            //        LicencePlate = table.Column<string>(type: "nvarchar(max)", nullable: false),
            //        VIN = table.Column<string>(type: "nvarchar(max)", nullable: false),
            //        Color = table.Column<long>(type: "bigint", nullable: false),
            //        Kilometer = table.Column<long>(type: "bigint", nullable: false),
            //        ModelName = table.Column<string>(type: "nvarchar(max)", nullable: false),
            //        ManufacturerName = table.Column<string>(type: "nvarchar(max)", nullable: false),
            //        ModelYear = table.Column<string>(type: "nvarchar(max)", nullable: false),
            //        CarImage = table.Column<byte[]>(type: "varbinary(max)", nullable: true)
            //    },
            //    constraints: table =>
            //    {
            //        table.PrimaryKey("PK_Output", x => x.id);
            //    });

            //migrationBuilder.CreateTable(
            //    name: "ServiceHistoryDTO",
            //    columns: table => new
            //    {
            //        UserModelsID = table.Column<long>(type: "bigint", nullable: false),
            //        Description = table.Column<string>(type: "nvarchar(max)", nullable: true),
            //        ServiceDate = table.Column<DateTime>(type: "datetime", nullable: true),
            //        ServiceKilometer = table.Column<long>(type: "bigint", nullable: true),
            //        StartPrice = table.Column<float>(type: "real", nullable: true),
            //        FinalPrice = table.Column<float>(type: "real", nullable: true),
            //        Name = table.Column<string>(type: "nvarchar(max)", nullable: true),
            //        Surname = table.Column<string>(type: "nvarchar(max)", nullable: true),
            //        LicencePlate = table.Column<string>(type: "nvarchar(max)", nullable: false),
            //        VIN = table.Column<string>(type: "nvarchar(max)", nullable: false),
            //        Color = table.Column<long>(type: "bigint", nullable: false),
            //        ModelName = table.Column<string>(type: "nvarchar(max)", nullable: false),
            //        ManufacturerName = table.Column<string>(type: "nvarchar(max)", nullable: false),
            //        ModelYear = table.Column<string>(type: "nvarchar(max)", nullable: false),
            //        CarImage = table.Column<byte[]>(type: "varbinary(max)", nullable: true)
            //    },
            //    constraints: table =>
            //    {
            //    });

            migrationBuilder.CreateTable(
                name: "Users",
                columns: table => new
                {
                    ID = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Surname = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Email = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Password = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    GarageID = table.Column<long>(type: "bigint", nullable: false),
                    UserType = table.Column<int>(type: "int", nullable: false),
                    Speciality = table.Column<long>(type: "bigint", nullable: true),
                    CreationDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    ModifiedDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    LastLoginDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    EnableAccess = table.Column<int>(type: "int", nullable: false),
                    UserPhoto = table.Column<byte[]>(type: "varbinary(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Users", x => x.ID);
                });

            migrationBuilder.CreateTable(
                name: "CarModelManufacturerYear",
                columns: table => new
                {
                    ID = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    CarManufacturerID = table.Column<long>(type: "bigint", nullable: false),
                    CarModelID = table.Column<long>(type: "bigint", nullable: false),
                    CarModelYearID = table.Column<long>(type: "bigint", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CarModelManufacturerYear", x => x.ID);
                    table.ForeignKey(
                        name: "FK_CarModelManufacturerYear_CarManufacturer_CarManufacturerID",
                        column: x => x.CarManufacturerID,
                        principalTable: "CarManufacturer",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_CarModelManufacturerYear_CarModelYear_CarModelYearID",
                        column: x => x.CarModelYearID,
                        principalTable: "CarModelYear",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_CarModelManufacturerYear_CarModels_CarModelID",
                        column: x => x.CarModelID,
                        principalTable: "CarModels",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "UserModels",
                columns: table => new
                {
                    ID = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    UserID = table.Column<long>(type: "bigint", nullable: false),
                    ModelManufacturerYearID = table.Column<long>(type: "bigint", nullable: false),
                    LicencePlate = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VIN = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Color = table.Column<long>(type: "bigint", nullable: true),
                    Kilometer = table.Column<long>(type: "bigint", nullable: true),
                    CarImage = table.Column<byte[]>(type: "varbinary(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UserModels", x => x.ID);
                    table.ForeignKey(
                        name: "FK_UserModels_CarModelManufacturerYear_ModelManufacturerYearID",
                        column: x => x.ModelManufacturerYearID,
                        principalTable: "CarModelManufacturerYear",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_UserModels_Users_UserID",
                        column: x => x.UserID,
                        principalTable: "Users",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.NoAction);
                });

            migrationBuilder.CreateTable(
                name: "ServiceHistory",
                columns: table => new
                {
                    ID = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    UserModelsID = table.Column<long>(type: "bigint", nullable: false),
                    Description = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ServiceDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    ServiceKilometer = table.Column<long>(type: "bigint", nullable: false),
                    EngineerID = table.Column<long>(type: "bigint", nullable: false),
                    StartPrice = table.Column<float>(type: "real", nullable: false),
                    DiscountPrice = table.Column<float>(type: "real", nullable: true),
                    DiscountPercentage = table.Column<float>(type: "real", nullable: true),
                    FinalPrice = table.Column<float>(type: "real", nullable: false),
                    StartingDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    FinishingDate = table.Column<DateTime>(type: "datetime", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ServiceHistory", x => x.ID);
                    table.ForeignKey(
                        name: "FK_ServiceHistory_UserModels_UserModelsID",
                        column: x => x.UserModelsID,
                        principalTable: "UserModels",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.NoAction);
                    table.ForeignKey(
                        name: "FK_ServiceHistory_Users_EngineerID",
                        column: x => x.EngineerID,
                        principalTable: "Users",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.NoAction);
                });

            migrationBuilder.InsertData(
                table: "CarEngineType",
                columns: new[] { "ID", "EngineType" },
                values: new object[,]
                {
                    { 1L, "--" },
                    { 2L, "Petrol" },
                    { 3L, "Diesel" },
                    { 4L, "Hybrid Petrol" },
                    { 5L, "Hybrid Diesel" },
                    { 6L, "LNG" },
                    { 7L, "CNG" },
                    { 8L, "Electric" }
                });

            migrationBuilder.InsertData(
                table: "CarManufacturer",
                columns: new[] { "ID", "ManufacturerName" },
                values: new object[,]
                {
                    { 1L, "Abarth" },
                    { 2L, "Alfa Romeo" },
                    { 3L, "Aston Martin" },
                    { 4L, "Audi" },
                    { 5L, "Bentley" },
                    { 6L, "BMW" },
                    { 7L, "Bugatti" },
                    { 8L, "Cadillac" },
                    { 9L, "Chevrolet" },
                    { 10L, "Chrysler" },
                    { 11L, "Citroën" },
                    { 12L, "Dacia" },
                    { 13L, "Daewoo" },
                    { 14L, "Daihatsu" },
                    { 15L, "Dodge" },
                    { 16L, "Donkervoort" },
                    { 17L, "DS" },
                    { 18L, "Ferrari" },
                    { 19L, "Fiat" },
                    { 20L, "Fisker" },
                    { 21L, "Ford" },
                    { 22L, "Honda" },
                    { 23L, "Hummer" },
                    { 24L, "Hyundai" },
                    { 25L, "Infiniti" },
                    { 26L, "Iveco" },
                    { 27L, "Jaguar" },
                    { 28L, "Jeep" },
                    { 29L, "Kia" },
                    { 30L, "KTM" },
                    { 31L, "Lada" },
                    { 32L, "Lamborghini" },
                    { 33L, "Lancia" },
                    { 34L, "Land Rover" },
                    { 35L, "Landwind" },
                    { 36L, "Lexus" },
                    { 37L, "Lotus" },
                    { 38L, "Maserati" },
                    { 39L, "Maybach" },
                    { 40L, "Mazda" },
                    { 41L, "McLaren" },
                    { 42L, "Mercedes-Benz" },
                    { 43L, "MG" },
                    { 44L, "Mini" },
                    { 45L, "Mitsubishi" },
                    { 46L, "Morgan" },
                    { 47L, "Nissan" },
                    { 48L, "Opel" },
                    { 49L, "Peugeot" },
                    { 50L, "Porsche" },
                    { 51L, "Renault" },
                    { 52L, "Rolls-Royce" },
                    { 53L, "Rover" },
                    { 54L, "Saab" },
                    { 55L, "Seat" },
                    { 56L, "Skoda" },
                    { 57L, "Smart" },
                    { 58L, "SsangYong" },
                    { 59L, "Subaru" },
                    { 60L, "Suzuki" },
                    { 61L, "Tesla" },
                    { 62L, "Toyota" },
                    { 63L, "Volkswagen" },
                    { 64L, "Volvo" }
                });

            migrationBuilder.InsertData(
                table: "CarModelYear",
                columns: new[] { "ID", "Description" },
                values: new object[,]
                {
                    { 1L, "1950" },
                    { 2L, "1951" },
                    { 3L, "1952" },
                    { 4L, "1953" },
                    { 5L, "1954" },
                    { 6L, "1955" },
                    { 7L, "1956" },
                    { 8L, "1957" },
                    { 9L, "1958" },
                    { 10L, "1959" },
                    { 11L, "1960" },
                    { 12L, "1961" },
                    { 13L, "1962" },
                    { 14L, "1963" },
                    { 15L, "1964" },
                    { 16L, "1965" },
                    { 17L, "1966" },
                    { 18L, "1967" },
                    { 19L, "1968" },
                    { 20L, "1969" },
                    { 21L, "1970" },
                    { 22L, "1971" },
                    { 23L, "1972" },
                    { 24L, "1973" },
                    { 25L, "1974" },
                    { 26L, "1975" },
                    { 27L, "1976" },
                    { 28L, "1977" },
                    { 29L, "1978" },
                    { 30L, "1979" },
                    { 31L, "1980" },
                    { 32L, "1981" },
                    { 33L, "1982" },
                    { 34L, "1983" },
                    { 35L, "1984" },
                    { 36L, "1985" },
                    { 37L, "1986" },
                    { 38L, "1987" },
                    { 39L, "1988" },
                    { 40L, "1989" },
                    { 41L, "1990" },
                    { 42L, "1991" },
                    { 43L, "1992" },
                    { 44L, "1993" },
                    { 45L, "1994" },
                    { 46L, "1995" },
                    { 47L, "1996" },
                    { 48L, "1997" },
                    { 49L, "1998" },
                    { 50L, "1999" },
                    { 51L, "2000" },
                    { 52L, "2001" },
                    { 53L, "2002" },
                    { 54L, "2003" },
                    { 55L, "2004" },
                    { 56L, "2005" },
                    { 57L, "2006" },
                    { 58L, "2007" },
                    { 59L, "2008" },
                    { 60L, "2009" },
                    { 61L, "2010" },
                    { 62L, "2011" },
                    { 63L, "2012" },
                    { 64L, "2013" },
                    { 65L, "2014" },
                    { 66L, "2015" },
                    { 67L, "2016" },
                    { 68L, "2017" },
                    { 69L, "2018" },
                    { 70L, "2019" },
                    { 71L, "2020" },
                    { 72L, "2021" },
                    { 73L, "2022" },
                    { 74L, "2023" }
                });

            migrationBuilder.InsertData(
                table: "CarModels",
                columns: new[] { "ID", "ModelName" },
                values: new object[,]
                {
                    { 1L, "Accent" },
                    { 2L, "Atos" },
                    { 3L, "Prime" },
                    { 4L, "Coupe" },
                    { 5L, "Elantra" },
                    { 6L, "Galloper" },
                    { 7L, "Genesis" },
                    { 8L, "Getz" },
                    { 9L, "Grandeur" },
                    { 10L, "H350" },
                    { 11L, "H1" },
                    { 12L, "H1Bus" },
                    { 13L, "H1Van" },
                    { 14L, "H200" },
                    { 15L, "i10" },
                    { 16L, "i20" },
                    { 17L, "i30" },
                    { 18L, "i30 CW" },
                    { 19L, "i40" },
                    { 20L, "i40 CW" },
                    { 21L, "ix20" },
                    { 22L, "ix35" },
                    { 23L, "ix55" },
                    { 24L, "Lantra" },
                    { 25L, "Matrix" },
                    { 26L, "SantaFe" },
                    { 27L, "Sonata" },
                    { 28L, "Terracan" },
                    { 29L, "Trajet" },
                    { 30L, "Tucson" },
                    { 31L, "Veloster" },
                    { 32L, "Kona" },
                    { 33L, "Bayon" },
                    { 34L, "145" },
                    { 35L, "146" },
                    { 36L, "147" },
                    { 37L, "155" },
                    { 38L, "156" },
                    { 39L, "156 Sportwagon" },
                    { 40L, "159" },
                    { 41L, "159 Sportwagon" },
                    { 42L, "164" },
                    { 43L, "166" },
                    { 44L, "4C" },
                    { 45L, "Brera" },
                    { 46L, "GTV" },
                    { 47L, "Mito" },
                    { 48L, "Crosswagon" },
                    { 49L, "Spider" },
                    { 50L, "GT" },
                    { 51L, "Giulietta" },
                    { 52L, "Giulia" },
                    { 53L, "4-Runner" },
                    { 54L, "Auris" },
                    { 55L, "Avensis" },
                    { 56L, "Avensis Combi" },
                    { 57L, "Avensis Van Verso" },
                    { 58L, "Aygo" },
                    { 59L, "Camry" },
                    { 60L, "Carina" },
                    { 61L, "Celica" },
                    { 62L, "Corolla" },
                    { 63L, "Corolla Combi" },
                    { 64L, "Corolla sedan" },
                    { 65L, "Corolla Verso" },
                    { 66L, "FJ Cruiser" },
                    { 67L, "GT86" },
                    { 68L, "Hiace" },
                    { 69L, "Hiace Van" },
                    { 70L, "Highlander" },
                    { 71L, "Hilux" },
                    { 72L, "Land Cruiser" },
                    { 73L, "MR2" },
                    { 74L, "Paseo" },
                    { 75L, "Picnic" },
                    { 76L, "Prius" },
                    { 77L, "RAV4" },
                    { 78L, "Sequoia" },
                    { 79L, "Starlet" },
                    { 80L, "Supra" },
                    { 81L, "Tundra" },
                    { 82L, "Urban Cruiser" },
                    { 83L, "Verso" },
                    { 84L, "Yaris" },
                    { 85L, "Yaris Verso" },
                    { 86L, "Alhambra," },
                    { 87L, "Altea" },
                    { 88L, "Altea XL" },
                    { 89L, "Arosa" },
                    { 90L, "Cordoba" },
                    { 91L, "Cordoba Vario" },
                    { 92L, "Exeo" },
                    { 93L, "Ibiza," },
                    { 94L, "Ibiza ST" },
                    { 95L, "Exeo ST" },
                    { 96L, "Leon," },
                    { 97L, "Leon ST" },
                    { 98L, "Inca" },
                    { 99L, "Mii," },
                    { 100L, "Toledo" },
                    { 101L, "Captur" },
                    { 102L, "Clio" },
                    { 103L, "Clio Grandtour" },
                    { 104L, "Espace" },
                    { 105L, "Express" },
                    { 106L, "Fluence" },
                    { 107L, "Grand Espace" },
                    { 108L, "Grand Modus" },
                    { 109L, "Grand Scenic" },
                    { 110L, "Kadjar" },
                    { 111L, "Kangoo" },
                    { 112L, "Kangoo Express" },
                    { 113L, "Koleos" },
                    { 114L, "Laguna" },
                    { 115L, "Laguna Grandtour" },
                    { 116L, "Latitude" },
                    { 117L, "Mascott" },
                    { 118L, "Mégane" },
                    { 119L, "Mégane CC" },
                    { 120L, "Mégane Combi" },
                    { 121L, "Mégane Grandtour" },
                    { 122L, "Mégane Coupé" },
                    { 123L, "Mégane Scénic" },
                    { 124L, "Scénic" },
                    { 125L, "Talisman" },
                    { 126L, "Talisman Grandtour" },
                    { 127L, "Thalia" },
                    { 128L, "Twingo" },
                    { 129L, "Wind" },
                    { 130L, "Zoé" },
                    { 131L, "1007" },
                    { 132L, "107" },
                    { 133L, "106" },
                    { 134L, "108" },
                    { 135L, "2008" },
                    { 136L, "205" },
                    { 137L, "205 Cabrio" },
                    { 138L, "206" },
                    { 139L, "206 CC" },
                    { 140L, "206 SW" },
                    { 141L, "207" },
                    { 142L, "207 CC" },
                    { 143L, "207 SW" },
                    { 144L, "306" },
                    { 145L, "307" },
                    { 146L, "307 CC" },
                    { 147L, "307 SW" },
                    { 148L, "308" },
                    { 149L, "308 CC" },
                    { 150L, "308 SW" },
                    { 151L, "309" },
                    { 152L, "4007" },
                    { 153L, "4008" },
                    { 154L, "405" },
                    { 155L, "406" },
                    { 156L, "407" },
                    { 157L, "407 SW" },
                    { 158L, "5008" },
                    { 159L, "508" },
                    { 160L, "508 SW" },
                    { 161L, "605" },
                    { 162L, "806" },
                    { 163L, "607" },
                    { 164L, "807" },
                    { 165L, "Bipper" },
                    { 166L, "RCZ Dokker" },
                    { 167L, "Duster" },
                    { 168L, "Lodgy" },
                    { 169L, "Logan" },
                    { 170L, "Logan MCV" },
                    { 171L, "Logan Van" },
                    { 172L, "Sandero" },
                    { 173L, "Solenza Berlingo" },
                    { 174L, "C-Crosser" },
                    { 175L, "C-Elissée" },
                    { 176L, "C-Zero" },
                    { 177L, "C1" },
                    { 178L, "C2" },
                    { 179L, "C3" },
                    { 180L, "C3 Picasso" },
                    { 181L, "C4" },
                    { 182L, "C4 Aircross" },
                    { 183L, "C4 Cactus" },
                    { 184L, "C4 Coupé" },
                    { 185L, "C4 Grand Picasso" },
                    { 186L, "C4 Sedan" },
                    { 187L, "C5" },
                    { 188L, "C5 Break" },
                    { 189L, "C5 Tourer" },
                    { 190L, "C6" },
                    { 191L, "C8" },
                    { 192L, "DS3" },
                    { 193L, "DS4" },
                    { 194L, "DS5" },
                    { 195L, "Evasion" },
                    { 196L, "Jumper" },
                    { 197L, "Jumpy" },
                    { 198L, "Saxo" },
                    { 199L, "Nemo" },
                    { 200L, "Xantia" },
                    { 201L, "Xsara Agila" },
                    { 202L, "Ampera" },
                    { 203L, "Antara" },
                    { 204L, "Astra" },
                    { 205L, "Astra cabrio" },
                    { 206L, "Astra caravan" },
                    { 207L, "Astra coupé" },
                    { 208L, "Calibra" },
                    { 209L, "Campo" },
                    { 210L, "Cascada" },
                    { 211L, "Corsa" },
                    { 212L, "Frontera" },
                    { 213L, "Insignia" },
                    { 214L, "Insignia kombi" },
                    { 215L, "Kadett" },
                    { 216L, "Meriva" },
                    { 217L, "Mokka" },
                    { 218L, "Movano" },
                    { 219L, "Omega" },
                    { 220L, "Signum" },
                    { 221L, "Vectra" },
                    { 222L, "Vectra Caravan" },
                    { 223L, "Vivaro" },
                    { 224L, "Vivaro Kombi" },
                    { 225L, "Zafira" },
                    { 226L, "Favorit" },
                    { 227L, "Felicia" },
                    { 228L, "Citigo" },
                    { 229L, "Fabia" },
                    { 230L, "Fabia Combi" },
                    { 231L, "Fabia Sedan" },
                    { 232L, "Felicia Combi" },
                    { 233L, "Octavia" },
                    { 234L, "Octavia Combi" },
                    { 235L, "Roomster" },
                    { 236L, "Yeti" },
                    { 237L, "Rapid" },
                    { 238L, "Rapid Spaceback" },
                    { 239L, "Superb" },
                    { 240L, "Superb Combi" },
                    { 241L, "Alero" },
                    { 242L, "Aveo" },
                    { 243L, "Camaro" },
                    { 244L, "Captiva" },
                    { 245L, "Corvette" },
                    { 246L, "Cruze" },
                    { 247L, "Cruze SW" },
                    { 248L, "Epica" },
                    { 249L, "Equinox" },
                    { 250L, "Evanda" },
                    { 251L, "HHR" },
                    { 252L, "Kalos" },
                    { 253L, "Lacetti" },
                    { 254L, "Lacetti SW" },
                    { 255L, "Lumina" },
                    { 256L, "Malibu" },
                    { 257L, "Matiz" },
                    { 258L, "Monte Carlo" },
                    { 259L, "Nubira" },
                    { 260L, "Orlando" },
                    { 261L, "Spark" },
                    { 262L, "Suburban" },
                    { 263L, "Tacuma" },
                    { 264L, "Tahoe" },
                    { 265L, "Trax" },
                    { 266L, "911 Carrera" },
                    { 267L, "911 Carrera Cabrio" },
                    { 268L, "911 Targa" },
                    { 269L, "911 Turbo" },
                    { 270L, "924" },
                    { 271L, "944" },
                    { 272L, "997" },
                    { 273L, "Boxster" },
                    { 274L, "Cayenne" },
                    { 275L, "Cayman" },
                    { 276L, "Macan" },
                    { 277L, "Panamera" },
                    { 278L, "Accord" },
                    { 279L, "Accord Coupé" },
                    { 280L, "Accord Tourer" },
                    { 281L, "City" },
                    { 282L, "Civic" },
                    { 283L, "Civic Aerodeck" },
                    { 284L, "Civic Coupé" },
                    { 285L, "Civic Tourer" },
                    { 286L, "Civic Type R" },
                    { 287L, "CR-V" },
                    { 288L, "CR-X" },
                    { 289L, "CR-Z" },
                    { 290L, "FR-V" },
                    { 291L, "HR-V" },
                    { 292L, "Insight" },
                    { 293L, "Integra" },
                    { 294L, "Jazz" },
                    { 295L, "Legend" },
                    { 296L, "Prelude" },
                    { 297L, "BRZ" },
                    { 298L, "Forester" },
                    { 299L, "Impreza" },
                    { 300L, "Impreza Wagon" },
                    { 301L, "Justy" },
                    { 302L, "Legacy" },
                    { 303L, "Legacy Wagon" },
                    { 304L, "Legacy Outback" },
                    { 305L, "Levorg" },
                    { 306L, "Outback" },
                    { 307L, "SVX" },
                    { 308L, "Tribeca" },
                    { 309L, "Tribeca B9" },
                    { 310L, "XV" },
                    { 311L, "121" },
                    { 312L, "2" },
                    { 313L, "3" },
                    { 314L, "323" },
                    { 315L, "323 Combi" },
                    { 316L, "323 Coupé" },
                    { 317L, "323 F" },
                    { 318L, "5" },
                    { 319L, "6" },
                    { 320L, "6 Combi" },
                    { 321L, "626" },
                    { 322L, "626 Combi" },
                    { 323L, "B-Fighter" },
                    { 324L, "B2500" },
                    { 325L, "BT" },
                    { 326L, "CX-3" },
                    { 327L, "CX-5" },
                    { 328L, "CX-7" },
                    { 329L, "CX-9" },
                    { 330L, "Demio" },
                    { 331L, "MPV" },
                    { 332L, "MX-3" },
                    { 333L, "MX-5" },
                    { 334L, "MX-6" },
                    { 335L, "Premacy" },
                    { 336L, "RX-7" },
                    { 337L, "RX-8" },
                    { 338L, "Xedox 6" },
                    { 339L, "3000 GT" },
                    { 340L, "ASX" },
                    { 341L, "Carisma" },
                    { 342L, "Colt" },
                    { 343L, "Colt CC" },
                    { 344L, "Eclipse" },
                    { 345L, "Fuso canter" },
                    { 346L, "Galant" },
                    { 347L, "Galant Combi" },
                    { 348L, "Grandis" },
                    { 349L, "L200" },
                    { 350L, "L200 Pick up" },
                    { 351L, "L200 Pick up Allrad" },
                    { 352L, "L300" },
                    { 353L, "Lancer" },
                    { 354L, "Lancer Combi" },
                    { 355L, "Lancer Evo" },
                    { 356L, "Lancer Sportback" },
                    { 357L, "Outlander" },
                    { 358L, "Pajero" },
                    { 359L, "Pajeto Pinin" },
                    { 360L, "Pajero Pinin Wagon" },
                    { 361L, "Pajero Sport" },
                    { 362L, "Pajero Wagon" },
                    { 363L, "Space Star" },
                    { 364L, "CT" },
                    { 365L, "GS" },
                    { 366L, "GS 300" },
                    { 367L, "GX" },
                    { 368L, "IS" },
                    { 369L, "IS 200" },
                    { 370L, "IS 250 C" },
                    { 371L, "IS-F" },
                    { 372L, "LS" },
                    { 373L, "LX" },
                    { 374L, "NX" },
                    { 375L, "RC F" },
                    { 376L, "RX" },
                    { 377L, "RX 300" },
                    { 378L, "RX 400h" },
                    { 379L, "RX 450h" },
                    { 380L, "SC 430" },
                    { 381L, "i3" },
                    { 382L, "i8" },
                    { 383L, "M3" },
                    { 384L, "M4" },
                    { 385L, "M5" },
                    { 386L, "M6" },
                    { 387L, "Rad 1" },
                    { 388L, "Rad 1 Cabrio" },
                    { 389L, "Rad 1 Coupé" },
                    { 390L, "Rad 2" },
                    { 391L, "Rad 2 Active Tourer" },
                    { 392L, "Rad 2 Coupé" },
                    { 393L, "Rad 2 Gran Tourer" },
                    { 394L, "Rad 3" },
                    { 395L, "Rad 3 Cabrio" },
                    { 396L, "Rad 3 Compact" },
                    { 397L, "Rad 3 Coupé" },
                    { 398L, "Rad 3 GT" },
                    { 399L, "Rad 3 Touring" },
                    { 400L, "Rad 4" },
                    { 401L, "Rad 4 Cabrio" },
                    { 402L, "Rad 4 Gran Coupé" },
                    { 403L, "Rad 5" },
                    { 404L, "Rad 5 GT" },
                    { 405L, "Rad 5 Touring" },
                    { 406L, "Rad 6" },
                    { 407L, "Rad 6 Cabrio" },
                    { 408L, "Rad 6 Coupé" },
                    { 409L, "Rad 6 Gran Coupé" },
                    { 410L, "Rad 7" },
                    { 411L, "Rad 8 Coupé" },
                    { 412L, "X1" },
                    { 413L, "X3" },
                    { 414L, "X4" },
                    { 415L, "X5" },
                    { 416L, "X6" },
                    { 417L, "Z3" },
                    { 418L, "Z3 Coupé" },
                    { 419L, "Z3 Roadster" },
                    { 420L, "Z4" },
                    { 421L, "Z4 Roadster" },
                    { 422L, "Amarok" },
                    { 423L, "Beetle" },
                    { 424L, "Bora" },
                    { 425L, "Bora Variant" },
                    { 426L, "Caddy" },
                    { 427L, "Caddy Van" },
                    { 428L, "Life" },
                    { 429L, "California" },
                    { 430L, "Caravelle" },
                    { 431L, "CC" },
                    { 432L, "Crafter" },
                    { 433L, "Crafter Van" },
                    { 434L, "Crafter Kombi" },
                    { 435L, "CrossTouran" },
                    { 436L, "Eos" },
                    { 437L, "Fox" },
                    { 438L, "Golf" },
                    { 439L, "Golf Cabrio" },
                    { 440L, "Golf Plus" },
                    { 441L, "Golf Sportvan" },
                    { 442L, "Golf Variant" },
                    { 443L, "Jetta" },
                    { 444L, "LT" },
                    { 445L, "Lupo" },
                    { 446L, "Multivan" },
                    { 447L, "New Beetle" },
                    { 448L, "New Beetle Cabrio" },
                    { 449L, "Passat" },
                    { 450L, "Passat Alltrack" },
                    { 451L, "Passat CC" },
                    { 452L, "Passat Variant" },
                    { 453L, "Passat Variant Van" },
                    { 454L, "Phaeton" },
                    { 455L, "Polo" },
                    { 456L, "Polo Van" },
                    { 457L, "Polo Variant" },
                    { 458L, "Scirocco" },
                    { 459L, "Sharan" },
                    { 460L, "T4" },
                    { 461L, "T4 Caravelle" },
                    { 462L, "T4 Multivan" },
                    { 463L, "T5" },
                    { 464L, "T5 Caravelle" },
                    { 465L, "T5 Multivan" },
                    { 466L, "T5 Transporter Shuttle" },
                    { 467L, "Tiguan" },
                    { 468L, "Touareg" },
                    { 469L, "Touran" },
                    { 470L, "Alto" },
                    { 471L, "Baleno" },
                    { 472L, "Baleno kombi" },
                    { 473L, "Grand Vitara" },
                    { 474L, "Grand Vitara XL-7" },
                    { 475L, "Ignis" },
                    { 476L, "Jimny" },
                    { 477L, "Kizashi" },
                    { 478L, "Liana" },
                    { 479L, "Samurai" },
                    { 480L, "Splash" },
                    { 481L, "Swift" },
                    { 482L, "SX4" },
                    { 483L, "SX4 Sedan" },
                    { 484L, "Vitara" },
                    { 485L, "Wagon R+" },
                    { 486L, "100 D" },
                    { 487L, "115" },
                    { 488L, "124" },
                    { 489L, "126" },
                    { 490L, "190" },
                    { 491L, "190 D" },
                    { 492L, "190 E" },
                    { 493L, "200 - 300" },
                    { 494L, "200 D" },
                    { 495L, "200 E" },
                    { 496L, "210 Van" },
                    { 497L, "210 kombi" },
                    { 498L, "310 Van" },
                    { 499L, "310 kombi" },
                    { 500L, "230 - 300 CE Coupé" },
                    { 501L, "260 - 560 SE" },
                    { 502L, "260 - 560 SEL" },
                    { 503L, "500 - 600 SEC Coupé" },
                    { 504L, "Trieda A" },
                    { 505L, "A" },
                    { 506L, "A L" },
                    { 507L, "AMG GT" },
                    { 508L, "Trieda B" },
                    { 509L, "Trieda C" },
                    { 510L, "C" },
                    { 511L, "C Sportcoupé" },
                    { 512L, "C T" },
                    { 513L, "Citan" },
                    { 514L, "CL" },
                    { 515L, "CL" },
                    { 516L, "CLA" },
                    { 517L, "CLC" },
                    { 518L, "CLK Cabrio" },
                    { 519L, "CLK Coupé" },
                    { 520L, "CLS" },
                    { 521L, "Trieda E" },
                    { 522L, "E" },
                    { 523L, "E Cabrio" },
                    { 524L, "E Coupé" },
                    { 525L, "E T" },
                    { 526L, "Trieda G" },
                    { 527L, "G Cabrio" },
                    { 528L, "GL" },
                    { 529L, "GLA" },
                    { 530L, "GLC" },
                    { 531L, "GLE" },
                    { 532L, "GLK" },
                    { 533L, "Trieda M" },
                    { 534L, "MB 100" },
                    { 535L, "Trieda R" },
                    { 536L, "Trieda S" },
                    { 537L, "S" },
                    { 538L, "S Coupé" },
                    { 539L, "SL" },
                    { 540L, "SLC" },
                    { 541L, "SLK" },
                    { 542L, "SLR" },
                    { 543L, "Sprinter" },
                    { 544L, "44994" },
                    { 545L, "9-3 Cabriolet" },
                    { 546L, "9-3 Coupé" },
                    { 547L, "9-3 SportCombi" },
                    { 548L, "45055" },
                    { 549L, "9-5 SportCombi" },
                    { 550L, "900" },
                    { 551L, "900 C" },
                    { 552L, "900 C Turbo" },
                    { 553L, "9000" },
                    { 554L, "100" },
                    { 555L, "100 Avant" },
                    { 556L, "80" },
                    { 557L, "80 Avant" },
                    { 558L, "80 Cabrio" },
                    { 559L, "90" },
                    { 560L, "A1" },
                    { 561L, "A2" },
                    { 562L, "A3" },
                    { 563L, "A3 Cabriolet" },
                    { 564L, "A3 Limuzina" },
                    { 565L, "A3 Sportback" },
                    { 566L, "A4" },
                    { 567L, "A4 Allroad" },
                    { 568L, "A4 Avant" },
                    { 569L, "A4 Cabriolet" },
                    { 570L, "A5" },
                    { 571L, "A5 Cabriolet" },
                    { 572L, "A5 Sportback" },
                    { 573L, "A6" },
                    { 574L, "A6 Allroad" },
                    { 575L, "A6 Avant" },
                    { 576L, "A7" },
                    { 577L, "A8" },
                    { 578L, "A8 Long" },
                    { 579L, "Q3" },
                    { 580L, "Q5" },
                    { 581L, "Q7" },
                    { 582L, "R8" },
                    { 583L, "RS4 Cabriolet" },
                    { 584L, "RS4/RS4 Avant" },
                    { 585L, "RS5" },
                    { 586L, "RS6 Avant" },
                    { 587L, "RS7" },
                    { 588L, "S3/S3 Sportback" },
                    { 589L, "S4 Cabriolet" },
                    { 590L, "S4/S4 Avant" },
                    { 591L, "S5/S5 Cabriolet" },
                    { 592L, "S6/RS6" },
                    { 593L, "S7" },
                    { 594L, "S8" },
                    { 595L, "SQ5" },
                    { 596L, "TT Coupé" },
                    { 597L, "TT Roadster" },
                    { 598L, "TTS" },
                    { 599L, "Avella" },
                    { 600L, "Besta" },
                    { 601L, "Carens" },
                    { 602L, "Carnival" },
                    { 603L, "Cee`d" },
                    { 604L, "Cee`d SW" },
                    { 605L, "Cerato" },
                    { 606L, "K 2500" },
                    { 607L, "Magentis" },
                    { 608L, "Opirus" },
                    { 609L, "Optima" },
                    { 610L, "Picanto" },
                    { 611L, "Pregio" },
                    { 612L, "Pride" },
                    { 613L, "Pro Cee`d" },
                    { 614L, "Rio" },
                    { 615L, "Rio Combi" },
                    { 616L, "Rio sedan" },
                    { 617L, "Sephia" },
                    { 618L, "Shuma" },
                    { 619L, "Sorento" },
                    { 620L, "Soul" },
                    { 621L, "Sportage" },
                    { 622L, "Venga" },
                    { 623L, "109" },
                    { 624L, "Defender" },
                    { 625L, "Discovery" },
                    { 626L, "Discovery Sport" },
                    { 627L, "Freelander" },
                    { 628L, "Range Rover" },
                    { 629L, "Range Rover Evoque" },
                    { 630L, "Range Rover Sport" },
                    { 631L, "Avenger" },
                    { 632L, "Caliber" },
                    { 633L, "Challenger" },
                    { 634L, "Charger" },
                    { 635L, "Grand Caravan" },
                    { 636L, "Journey" },
                    { 637L, "Magnum" },
                    { 638L, "Nitro" },
                    { 639L, "RAM" },
                    { 640L, "Stealth" },
                    { 641L, "Viper" },
                    { 642L, "300 C" },
                    { 643L, "300 C Touring" },
                    { 644L, "300 M" },
                    { 645L, "Crossfire" },
                    { 646L, "Grand Voyager" },
                    { 647L, "LHS" },
                    { 648L, "Neon" },
                    { 649L, "Pacifica" },
                    { 650L, "Plymouth" },
                    { 651L, "PT Cruiser" },
                    { 652L, "Sebring" },
                    { 653L, "Sebring Convertible" },
                    { 654L, "Stratus" },
                    { 655L, "Stratus Cabrio" },
                    { 656L, "Town & Country" },
                    { 657L, "Voyager" },
                    { 658L, "Aerostar" },
                    { 659L, "B-Max" },
                    { 660L, "C-Max" },
                    { 661L, "Cortina" },
                    { 662L, "Cougar" },
                    { 663L, "Edge" },
                    { 664L, "Escort" },
                    { 665L, "Escort Cabrio" },
                    { 666L, "Escort kombi" },
                    { 667L, "Explorer" },
                    { 668L, "F-150" },
                    { 669L, "F-250" },
                    { 670L, "Fiesta" },
                    { 671L, "Focus" },
                    { 672L, "Focus C-Max" },
                    { 673L, "Focus CC" },
                    { 674L, "Focus kombi" },
                    { 675L, "Fusion" },
                    { 676L, "Galaxy" },
                    { 677L, "Grand C-Max" },
                    { 678L, "Ka" },
                    { 679L, "Kuga" },
                    { 680L, "Maverick" },
                    { 681L, "Mondeo" },
                    { 682L, "Mondeo Combi" },
                    { 683L, "Mustang" },
                    { 684L, "Orion" },
                    { 685L, "Puma" },
                    { 686L, "Ranger" },
                    { 687L, "S-Max" },
                    { 688L, "Sierra" },
                    { 689L, "Street Ka" },
                    { 690L, "Tourneo Connect" },
                    { 691L, "Tourneo Custom" },
                    { 692L, "Transit" },
                    { 693L, "Transit" },
                    { 694L, "Transit Bus" },
                    { 695L, "Transit Connect LWB" },
                    { 696L, "Transit Courier" },
                    { 697L, "Transit Custom" },
                    { 698L, "Transit kombi" },
                    { 699L, "Transit Tourneo" },
                    { 700L, "Transit Valnik" },
                    { 701L, "Transit Van" },
                    { 702L, "Transit Van 350" },
                    { 703L, "Windstar" },
                    { 704L, "H2" },
                    { 705L, "H3" },
                    { 706L, "EX" },
                    { 707L, "FX" },
                    { 708L, "G" },
                    { 709L, "G Coupé" },
                    { 710L, "M" },
                    { 711L, "Q" },
                    { 712L, "QX" },
                    { 713L, "Daimler" },
                    { 714L, "F-Pace" },
                    { 715L, "F-Type" },
                    { 716L, "S-Type" },
                    { 717L, "Sovereign" },
                    { 718L, "X-Type" },
                    { 719L, "X-type Estate" },
                    { 720L, "XE" },
                    { 721L, "XF" },
                    { 722L, "XJ" },
                    { 723L, "XJ12" },
                    { 724L, "XJ6" },
                    { 725L, "XJ8" },
                    { 726L, "XJ8" },
                    { 727L, "XJR" },
                    { 728L, "XK" },
                    { 729L, "XK8 Convertible" },
                    { 730L, "XKR" },
                    { 731L, "XKR Convertible" },
                    { 732L, "Cherokee" },
                    { 733L, "Commander" },
                    { 734L, "Compass" },
                    { 735L, "Grand Cherokee" },
                    { 736L, "Patriot" },
                    { 737L, "Renegade" },
                    { 738L, "Wrangler" },
                    { 739L, "100 NX" },
                    { 740L, "200 SX" },
                    { 741L, "350 Z" },
                    { 742L, "350 Z Roadster" },
                    { 743L, "370 Z" },
                    { 744L, "Almera" },
                    { 745L, "Almera Tino" },
                    { 746L, "Cabstar E - T" },
                    { 747L, "Cabstar TL2 Valnik" },
                    { 748L, "e-NV200" },
                    { 749L, "GT-R" },
                    { 750L, "Insterstar" },
                    { 751L, "Juke" },
                    { 752L, "King Cab" },
                    { 753L, "Leaf" },
                    { 754L, "Maxima" },
                    { 755L, "Maxima QX" },
                    { 756L, "Micra" },
                    { 757L, "Murano" },
                    { 758L, "Navara" },
                    { 759L, "Note" },
                    { 760L, "NP300 Pickup" },
                    { 761L, "NV200" },
                    { 762L, "NV400" },
                    { 763L, "Pathfinder" },
                    { 764L, "Patrol" },
                    { 765L, "Patrol GR" },
                    { 766L, "Pickup" },
                    { 767L, "Pixo" },
                    { 768L, "Primastar" },
                    { 769L, "Primastar Combi" },
                    { 770L, "Primera" },
                    { 771L, "Primera Combi" },
                    { 772L, "Pulsar" },
                    { 773L, "Qashqai" },
                    { 774L, "Serena" },
                    { 775L, "Sunny" },
                    { 776L, "Terrano" },
                    { 777L, "Tiida" },
                    { 778L, "Trade" },
                    { 779L, "Vanette Cargo" },
                    { 780L, "X-Trail" },
                    { 781L, "240" },
                    { 782L, "340" },
                    { 783L, "360" },
                    { 784L, "460" },
                    { 785L, "850" },
                    { 786L, "850 kombi" },
                    { 787L, "C30" },
                    { 788L, "C70" },
                    { 789L, "C70 Cabrio" },
                    { 790L, "C70 Coupé" },
                    { 791L, "S40" },
                    { 792L, "S60" },
                    { 793L, "S70" },
                    { 794L, "S80" },
                    { 795L, "S90" },
                    { 796L, "V40" },
                    { 797L, "V50" },
                    { 798L, "V60" },
                    { 799L, "V70" },
                    { 800L, "V90" },
                    { 801L, "XC60" },
                    { 802L, "XC70" },
                    { 803L, "XC90" },
                    { 804L, "Espero" },
                    { 805L, "Kalos" },
                    { 806L, "Lacetti" },
                    { 807L, "Lanos" },
                    { 808L, "Leganza" },
                    { 809L, "Lublin" },
                    { 810L, "Matiz" },
                    { 811L, "Nexia" },
                    { 812L, "Nubira" },
                    { 813L, "Nubira kombi" },
                    { 814L, "Racer" },
                    { 815L, "Tacuma" },
                    { 816L, "Tico" },
                    { 817L, "1100" },
                    { 818L, "126" },
                    { 819L, "500" },
                    { 820L, "500L" },
                    { 821L, "500X" },
                    { 822L, "850" },
                    { 823L, "Barchetta" },
                    { 824L, "Brava" },
                    { 825L, "Cinquecento" },
                    { 826L, "Coupé" },
                    { 827L, "Croma" },
                    { 828L, "Doblo" },
                    { 829L, "Doblo Cargo" },
                    { 830L, "Doblo Cargo Combi" },
                    { 831L, "Ducato" },
                    { 832L, "Ducato Van" },
                    { 833L, "Ducato Kombi" },
                    { 834L, "Ducato Podvozok" },
                    { 835L, "Florino" },
                    { 836L, "Florino Combi" },
                    { 837L, "Freemont" },
                    { 838L, "Grande Punto" },
                    { 839L, "Idea" },
                    { 840L, "Linea" },
                    { 841L, "Marea" },
                    { 842L, "Marea Weekend" },
                    { 843L, "Multipla" },
                    { 844L, "Palio Weekend" },
                    { 845L, "Panda" },
                    { 846L, "Panda Van" },
                    { 847L, "Punto" },
                    { 848L, "Punto Cabriolet" },
                    { 849L, "Punto Evo" },
                    { 850L, "Punto Van" },
                    { 851L, "Qubo" },
                    { 852L, "Scudo" },
                    { 853L, "Scudo Van" },
                    { 854L, "Scudo Kombi" },
                    { 855L, "Sedici" },
                    { 856L, "Seicento" },
                    { 857L, "Stilo" },
                    { 858L, "Stilo Multiwagon" },
                    { 859L, "Strada" },
                    { 860L, "Talento" },
                    { 861L, "Tipo" },
                    { 862L, "Ulysse" },
                    { 863L, "Uno" },
                    { 864L, "X1/9" },
                    { 865L, "Cooper" },
                    { 866L, "Cooper Cabrio" },
                    { 867L, "Cooper Clubman" },
                    { 868L, "Cooper D" },
                    { 869L, "Cooper D Clubman" },
                    { 870L, "Cooper S" },
                    { 871L, "Cooper S Cabrio" },
                    { 872L, "Cooper S Clubman" },
                    { 873L, "Countryman" },
                    { 874L, "Mini One" },
                    { 875L, "One D" },
                    { 876L, "200" },
                    { 877L, "214" },
                    { 878L, "218" },
                    { 879L, "25" },
                    { 880L, "400" },
                    { 881L, "414" },
                    { 882L, "416" },
                    { 883L, "620" },
                    { 884L, "75" },
                    { 885L, "Cabrio" },
                    { 886L, "City-Coupé" },
                    { 887L, "Compact Pulse" },
                    { 888L, "Forfour" },
                    { 889L, "Fortwo cabrio" },
                    { 890L, "Fortwo coupé" },
                    { 891L, "Roadster" }
                });

            migrationBuilder.InsertData(
                table: "EngineerSpeciality",
                columns: new[] { "ID", "Speciality" },
                values: new object[,]
                {
                    { 1L, "Ηλεκτρολόγος" },
                    { 2L, "Φαναρτζής" },
                    { 3L, "Βαφέας" },
                    { 4L, "Τεχνικός Παρμπρίζ" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "ID", "CreationDate", "Email", "EnableAccess", "GarageID", "LastLoginDate", "ModifiedDate", "Name", "Password", "Speciality", "Surname", "UserPhoto", "UserType" },
                values: new object[,]
                {
                    { 1L, new DateTime(2022, 1, 6, 14, 5, 14, 258, DateTimeKind.Unspecified), "atselios@classter.com", 1, 0L, null, null, "Alexandros", "1", null, "Tselios", null, 1 },
                    { 2L, new DateTime(2022, 2, 6, 9, 19, 46, 369, DateTimeKind.Unspecified), "efi.vanni@gmail.com", 1, 0L, null, null, "Efthumia", "f1234!", null, "Varvagianni", null, 2 },
                    { 3L, new DateTime(2022, 12, 15, 22, 19, 46, 456, DateTimeKind.Unspecified), "kkitsikou@hotmail.com", 1, 0L, null, null, "Kostas", "gafa#$#", null, "Kitsikou", null, 2 },
                    { 4L, new DateTime(2022, 12, 24, 13, 42, 34, 566, DateTimeKind.Unspecified), "mpapadopoulos@yahoo.gr", 2, 0L, null, null, "Marios", "MP1234@?", null, "Papadopoulos", null, 2 },
                    { 5L, new DateTime(2023, 2, 3, 20, 8, 23, 860, DateTimeKind.Unspecified), "konpapa@yahoo.gr", 1, 0L, null, null, "Κωνσταντίνος", "DfG34#$%^", 3L, "Παπαδόπουλος", null, 3 },
                    { 6L, new DateTime(2023, 6, 2, 16, 37, 48, 180, DateTimeKind.Local).AddTicks(7589), "mmichail@gmail.com", 1, 0L, null, null, "Μιχάλης", "KavMixalis$%", 2L, "Μιχαήλ", null, 3 }
                });

            migrationBuilder.InsertData(
                table: "CarModelManufacturerYear",
                columns: new[] { "ID", "CarManufacturerID", "CarModelID", "CarModelYearID" },
                values: new object[,]
                {
                    { 1L, 24L, 16L, 59L },
                    { 2L, 24L, 16L, 60L },
                    { 3L, 24L, 16L, 61L },
                    { 4L, 24L, 16L, 62L },
                    { 5L, 24L, 16L, 63L },
                    { 6L, 24L, 16L, 64L },
                    { 7L, 24L, 16L, 65L },
                    { 8L, 24L, 16L, 66L },
                    { 9L, 24L, 16L, 67L },
                    { 10L, 24L, 16L, 68L },
                    { 11L, 24L, 16L, 69L },
                    { 12L, 24L, 16L, 70L },
                    { 13L, 24L, 16L, 71L },
                    { 14L, 24L, 16L, 72L },
                    { 15L, 24L, 16L, 73L },
                    { 16L, 24L, 16L, 74L },
                    { 17L, 24L, 17L, 58L },
                    { 18L, 24L, 17L, 59L },
                    { 19L, 24L, 17L, 60L },
                    { 20L, 24L, 17L, 61L },
                    { 21L, 24L, 17L, 62L },
                    { 22L, 24L, 17L, 63L },
                    { 23L, 24L, 17L, 64L },
                    { 24L, 24L, 17L, 65L },
                    { 25L, 24L, 17L, 66L },
                    { 26L, 24L, 17L, 67L },
                    { 27L, 24L, 17L, 68L },
                    { 28L, 24L, 17L, 69L },
                    { 29L, 24L, 17L, 70L },
                    { 30L, 24L, 17L, 71L },
                    { 31L, 24L, 17L, 72L },
                    { 32L, 24L, 17L, 73L },
                    { 33L, 24L, 17L, 74L },
                    { 34L, 24L, 15L, 58L },
                    { 35L, 24L, 15L, 59L },
                    { 36L, 24L, 15L, 60L },
                    { 37L, 24L, 15L, 61L },
                    { 38L, 24L, 15L, 62L },
                    { 39L, 24L, 15L, 63L },
                    { 40L, 24L, 15L, 64L },
                    { 41L, 24L, 15L, 65L },
                    { 42L, 24L, 15L, 66L },
                    { 43L, 24L, 15L, 67L },
                    { 44L, 24L, 15L, 68L },
                    { 45L, 24L, 15L, 69L },
                    { 46L, 24L, 15L, 70L },
                    { 47L, 24L, 15L, 71L },
                    { 48L, 24L, 15L, 72L },
                    { 49L, 24L, 15L, 73L },
                    { 50L, 24L, 15L, 74L },
                    { 51L, 2L, 51L, 61L },
                    { 52L, 2L, 51L, 62L },
                    { 53L, 2L, 51L, 63L },
                    { 54L, 2L, 51L, 64L },
                    { 55L, 2L, 51L, 65L },
                    { 56L, 2L, 51L, 66L },
                    { 57L, 2L, 51L, 67L },
                    { 58L, 2L, 51L, 68L },
                    { 59L, 2L, 51L, 69L },
                    { 60L, 2L, 51L, 70L },
                    { 61L, 2L, 51L, 71L },
                    { 62L, 62L, 84L, 50L },
                    { 63L, 62L, 84L, 51L },
                    { 64L, 62L, 84L, 52L },
                    { 65L, 62L, 84L, 53L },
                    { 66L, 62L, 84L, 54L },
                    { 67L, 62L, 84L, 55L },
                    { 68L, 62L, 84L, 56L },
                    { 69L, 62L, 84L, 57L },
                    { 70L, 62L, 84L, 58L },
                    { 71L, 62L, 84L, 59L },
                    { 72L, 62L, 84L, 60L },
                    { 73L, 62L, 84L, 61L },
                    { 74L, 62L, 84L, 62L },
                    { 75L, 62L, 84L, 63L },
                    { 76L, 62L, 84L, 64L },
                    { 77L, 62L, 84L, 65L },
                    { 78L, 62L, 84L, 66L },
                    { 79L, 62L, 84L, 67L },
                    { 80L, 62L, 84L, 68L },
                    { 81L, 62L, 84L, 69L },
                    { 82L, 62L, 84L, 70L },
                    { 83L, 62L, 84L, 71L },
                    { 84L, 62L, 84L, 72L },
                    { 85L, 62L, 84L, 73L },
                    { 86L, 62L, 84L, 74L },
                    { 87L, 62L, 76L, 52L },
                    { 88L, 62L, 76L, 53L },
                    { 89L, 62L, 76L, 54L },
                    { 90L, 62L, 76L, 55L },
                    { 91L, 62L, 76L, 56L },
                    { 92L, 62L, 76L, 57L },
                    { 93L, 62L, 76L, 58L },
                    { 94L, 62L, 76L, 59L },
                    { 95L, 62L, 76L, 60L },
                    { 96L, 62L, 76L, 61L },
                    { 97L, 62L, 76L, 62L },
                    { 98L, 62L, 76L, 63L },
                    { 99L, 62L, 76L, 64L },
                    { 100L, 62L, 76L, 65L },
                    { 101L, 62L, 76L, 66L },
                    { 102L, 62L, 76L, 67L },
                    { 103L, 62L, 76L, 68L },
                    { 104L, 62L, 76L, 69L },
                    { 105L, 62L, 76L, 70L },
                    { 106L, 62L, 76L, 71L },
                    { 107L, 62L, 76L, 72L },
                    { 108L, 62L, 76L, 73L },
                    { 109L, 62L, 76L, 74L },
                    { 110L, 2L, 34L, 1L },
                    { 111L, 2L, 35L, 1L },
                    { 112L, 2L, 36L, 1L },
                    { 113L, 2L, 37L, 1L },
                    { 114L, 2L, 38L, 1L },
                    { 115L, 2L, 39L, 1L },
                    { 116L, 2L, 40L, 1L },
                    { 117L, 2L, 41L, 1L },
                    { 118L, 2L, 42L, 1L },
                    { 119L, 2L, 43L, 1L },
                    { 120L, 2L, 44L, 1L },
                    { 121L, 2L, 45L, 1L },
                    { 122L, 2L, 46L, 1L },
                    { 123L, 2L, 47L, 1L },
                    { 124L, 2L, 48L, 1L },
                    { 125L, 2L, 49L, 1L },
                    { 126L, 2L, 50L, 1L },
                    { 127L, 2L, 52L, 1L },
                    { 128L, 24L, 1L, 1L },
                    { 129L, 24L, 2L, 1L },
                    { 130L, 24L, 3L, 1L },
                    { 131L, 24L, 4L, 1L },
                    { 132L, 24L, 5L, 1L },
                    { 133L, 24L, 6L, 1L },
                    { 134L, 24L, 7L, 1L },
                    { 135L, 24L, 8L, 1L },
                    { 136L, 24L, 9L, 1L },
                    { 137L, 24L, 10L, 1L },
                    { 138L, 24L, 11L, 1L },
                    { 139L, 24L, 12L, 1L },
                    { 140L, 24L, 13L, 1L },
                    { 141L, 24L, 14L, 1L },
                    { 142L, 24L, 18L, 1L },
                    { 143L, 24L, 19L, 1L },
                    { 144L, 24L, 20L, 1L },
                    { 145L, 24L, 21L, 1L },
                    { 146L, 24L, 22L, 1L },
                    { 147L, 24L, 23L, 1L },
                    { 148L, 24L, 24L, 1L },
                    { 149L, 24L, 25L, 1L },
                    { 150L, 24L, 26L, 1L },
                    { 151L, 24L, 27L, 1L },
                    { 152L, 24L, 28L, 1L },
                    { 153L, 24L, 29L, 1L },
                    { 154L, 24L, 30L, 1L },
                    { 155L, 24L, 31L, 1L },
                    { 156L, 24L, 32L, 1L },
                    { 157L, 24L, 33L, 1L }
                });

            migrationBuilder.InsertData(
    table: "UserModels",
    columns: new[] { "ID", "UserID", "ModelManufacturerYearID", "LicencePlate", "VIN", "Color", "Kilometer" },
    values: new object[,]
    {
                                {1L, 1L, 56L, "KBT5670", "ZAR94000007368150", 101, 156125},
                                {2L, 1L, 81L, "EYB7174", "VNKKG3D330A048555", 142, 27450},
                                {3L, 1L, 3L,"NIZ2654", "NLHBA51BABZ014926", 4, 88956},
                                {4L, 2L, 5L,"XEZ6532", "KHX94000007259841", 5, 220653},
                                {5L, 2L, 6L, "KBH1452", "JNKCV61E09M303716", 6, 65402},
                                {6L, 3L, 6L, "AHZ1495", "JH4DA9460MS032070", 6, 9563}
    });

            migrationBuilder.InsertData(
                table: "ServiceHistory",
                columns: new[] { "ID", "Description", "DiscountPercentage", "DiscountPrice", "EngineerID", "FinalPrice", "FinishingDate", "ServiceDate", "ServiceKilometer", "StartPrice", "StartingDate", "UserModelsID" },
                values: new object[,]
                {
                    { 1L, "Αλλαγή λαδιών", null, null, 5L, 55f, new DateTime(2022, 12, 7, 13, 24, 10, 552, DateTimeKind.Unspecified), new DateTime(2022, 12, 6, 20, 40, 10, 552, DateTimeKind.Unspecified), 65080L, 55f, new DateTime(2022, 12, 7, 13, 24, 10, 552, DateTimeKind.Unspecified), 1L },
                    { 2L, "Αλλαγή ιμάντα χρονισμού", null, null, 5L, 95f, new DateTime(2023, 2, 6, 20, 40, 10, 552, DateTimeKind.Unspecified), new DateTime(2023, 2, 6, 20, 40, 10, 552, DateTimeKind.Unspecified), 70898L, 95f, new DateTime(2023, 2, 6, 15, 38, 10, 552, DateTimeKind.Unspecified), 1L },
                    { 3L, "Αλλαγή Ελαστικων", null, null, 5L, 100f, new DateTime(2023, 2, 6, 20, 40, 10, 552, DateTimeKind.Unspecified), new DateTime(2023, 4, 6, 20, 40, 10, 552, DateTimeKind.Unspecified), 85365L, 100f, new DateTime(2023, 4, 6, 15, 38, 10, 552, DateTimeKind.Unspecified), 1L }
                });

            var GetCustomerCars = @"CREATE PROCEDURE GetCustomerCars
                -- Add the parameters for the stored procedure here
                @UserID BIGINT
                AS
                BEGIN
	                SET NOCOUNT ON;
	                SELECT UM.ID, 
		                   UM.UserID, 
		                   CMAN.ManufacturerName, 
		                   CM.ModelName, 
		                   CMY.Description AS ModelYear, 
		                   UM.LicencePlate, 
		                   UM.VIN, 
		                   UM.Color, 
		                   UM.Kilometer,
						   UM.CarImage
	                FROM UserModels UM
		                 INNER JOIN CarModelManufacturerYear CMMY ON CMMY.ID = um.ModelManufacturerYearID
		                 INNER JOIN CarModels CM ON CM.ID = CMMY.CarModelID
		                 INNER JOIN CarManufacturer CMAN ON CMAN.ID = CMMY.CarManufacturerID
		                 INNER JOIN CarModelYear CMY ON CMY.ID = CMMY.CarModelYearID
	                WHERE UserId = @UserID;
                END";

            migrationBuilder.Sql(GetCustomerCars);

            var GetCustomerCar = @"CREATE PROCEDURE GetCustomerCar
                -- Add the parameters for the stored procedure here
                @UserModelID BIGINT
                AS
                BEGIN
	                SET NOCOUNT ON;
	                SELECT UM.ID, 
		                   UM.UserID, 
		                   CMAN.ManufacturerName, 
		                   CM.ModelName, 
		                   CMY.Description AS ModelYear, 
		                   UM.LicencePlate, 
		                   UM.VIN, 
		                   UM.Color, 
		                   UM.Kilometer,
						   UM.CarImage
	                FROM UserModels UM
		                 INNER JOIN CarModelManufacturerYear CMMY ON CMMY.ID = um.ModelManufacturerYearID
		                 INNER JOIN CarModels CM ON CM.ID = CMMY.CarModelID
		                 INNER JOIN CarManufacturer CMAN ON CMAN.ID = CMMY.CarManufacturerID
		                 INNER JOIN CarModelYear CMY ON CMY.ID = CMMY.CarModelYearID
	                WHERE UM.ID = @UserModelID;
                END";

            migrationBuilder.Sql(GetCustomerCar);

            var GetCarServiceHistory = @"CREATE PROCEDURE[dbo].[GetCarServiceHistory]
                -- Add the parameters for the stored procedure here
                @UserModelsID BIGINT
                AS
                BEGIN
	                SET NOCOUNT ON;
                    SELECT SH.Description, 
                           SH.ServiceDate, 
                           SH.StartingDate, 
                           SH.FinishingDate, 
                           SH.ServiceKilometer, 
                           SH.StartPrice, 
                           SH.FinalPrice, 
                           UE.Surname, 
                           UE.Name, 
                           CMAN.ManufacturerName, 
                           CM.ModelName, 
                           CMY.Description AS ModelYear, 
                           UM.ID AS UserModelsID, 
                           UM.LicencePlate, 
                           UM.VIN, 
                           UM.Color, 
                           UM.Kilometer, 
                           UM.CarImage
                    FROM UserModels UM
                         INNER JOIN CarModelManufacturerYear CMMY ON CMMY.ID = um.ModelManufacturerYearID
                         INNER JOIN CarModels CM ON CM.ID = CMMY.CarModelID
                         INNER JOIN CarManufacturer CMAN ON CMAN.ID = CMMY.CarManufacturerID
                         INNER JOIN CarModelYear CMY ON CMY.ID = CMMY.CarModelYearID
                         LEFT OUTER JOIN ServiceHistory SH ON UM.ID = SH.UserModelsID
                         LEFT OUTER JOIN Users UE ON UE.ID = EngineerID
                    WHERE SH.UserModelsID = @UserModelsID
                    ORDER BY SH.ServiceDate DESC;
                END";

            migrationBuilder.Sql(GetCarServiceHistory);

            migrationBuilder.CreateIndex(
                name: "IX_CarModelManufacturerYear_CarManufacturerID",
                table: "CarModelManufacturerYear",
                column: "CarManufacturerID");

            migrationBuilder.CreateIndex(
                name: "IX_CarModelManufacturerYear_CarModelID",
                table: "CarModelManufacturerYear",
                column: "CarModelID");

            migrationBuilder.CreateIndex(
                name: "IX_CarModelManufacturerYear_CarModelYearID",
                table: "CarModelManufacturerYear",
                column: "CarModelYearID");

            migrationBuilder.CreateIndex(
                name: "IX_ServiceHistory_EngineerID",
                table: "ServiceHistory",
                column: "EngineerID");

            migrationBuilder.CreateIndex(
                name: "IX_ServiceHistory_UserModelsID",
                table: "ServiceHistory",
                column: "UserModelsID");

            migrationBuilder.CreateIndex(
                name: "IX_UserModels_ModelManufacturerYearID",
                table: "UserModels",
                column: "ModelManufacturerYearID");

            migrationBuilder.CreateIndex(
                name: "IX_UserModels_UserID",
                table: "UserModels",
                column: "UserID");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CarEngineType");

            migrationBuilder.DropTable(
                name: "EngineerSpeciality");

            migrationBuilder.DropTable(
                name: "Output");

            migrationBuilder.DropTable(
                name: "ServiceHistory");

            migrationBuilder.DropTable(
                name: "ServiceHistoryDTO");

            migrationBuilder.DropTable(
                name: "UserModels");

            migrationBuilder.DropTable(
                name: "CarModelManufacturerYear");

            migrationBuilder.DropTable(
                name: "Users");

            migrationBuilder.DropTable(
                name: "CarManufacturer");

            migrationBuilder.DropTable(
                name: "CarModelYear");

            migrationBuilder.DropTable(
                name: "CarModels");
        }
    }
}
