using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace GarageAPI.Migrations
{
    /// <inheritdoc />
    public partial class InitialMigration : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "CarManufacturer",
                columns: table => new
                {
                    ID = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    ManufacturerName = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CarManufacturer", x => x.ID);
                });

            migrationBuilder.CreateTable(
                name: "CarModels",
                columns: table => new
                {
                    ID = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    ModelName = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CarModels", x => x.ID);
                });

            migrationBuilder.CreateTable(
                name: "CarModelYear",
                columns: table => new
                {
                    ID = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Description = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CarModelYear", x => x.ID);
                });

            migrationBuilder.CreateTable(
                name: "Users",
                columns: table => new
                {
                    ID = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Surname = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Email = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Password = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    GarageID = table.Column<long>(type: "bigint", nullable: false),
                    UserType = table.Column<long>(type: "bigint", nullable: true),
                    CreationDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    ModifiedDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    LastLoginDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    EnableAccess = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Users", x => x.ID);
                });

            migrationBuilder.CreateTable(
                name: "CarModelManufacturerYear",
                columns: table => new
                {
                    ID = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    CarManufacturerID = table.Column<long>(type: "bigint", nullable: false),
                    CarModelID = table.Column<long>(type: "bigint", nullable: false),
                    CarModelYearID = table.Column<long>(type: "bigint", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CarModelManufacturerYear", x => x.ID);
                    table.ForeignKey(
                        name: "FK_CarModelManufacturerYear_CarManufacturer_CarManufacturerID",
                        column: x => x.CarManufacturerID,
                        principalTable: "CarManufacturer",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_CarModelManufacturerYear_CarModelYear_CarModelYearID",
                        column: x => x.CarModelYearID,
                        principalTable: "CarModelYear",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.NoAction);
                    table.ForeignKey(
                        name: "FK_CarModelManufacturerYear_CarModels_CarModelID",
                        column: x => x.CarModelID,
                        principalTable: "CarModels",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "UserModels",
                columns: table => new
                {
                    ID = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    UserID = table.Column<long>(type: "bigint", nullable: false),
                    ModelManufacturerYearID = table.Column<long>(type: "bigint", nullable: false),
                    ModelYearID = table.Column<long>(type: "bigint", nullable: false),
                    LicencePlate = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VIN = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Color = table.Column<long>(type: "bigint", nullable: true),
                    Kilometer = table.Column<long>(type: "bigint", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UserModels", x => x.ID);
                    table.ForeignKey(
                        name: "FK_UserModels_CarModelManufacturerYear_ModelManufacturerYearID",
                        column: x => x.ModelManufacturerYearID,
                        principalTable: "CarModelManufacturerYear",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_UserModels_CarModelYear_ModelYearID",
                        column: x => x.ModelYearID,
                        principalTable: "CarModelYear",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_UserModels_Users_UserID",
                        column: x => x.UserID,
                        principalTable: "Users",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "CarManufacturer",
                columns: new[] { "ID", "ManufacturerName" },
                values: new object[,]
                {
                    { 1L, "Abarth" },
                    { 2L, "Alfa Romeo" },
                    { 3L, "Aston Martin" },
                    { 4L, "Audi" },
                    { 5L, "Bentley" },
                    { 6L, "BMW" },
                    { 7L, "Bugatti" },
                    { 8L, "Cadillac" },
                    { 9L, "Chevrolet" },
                    { 10L, "Chrysler" },
                    { 11L, "Citroën" },
                    { 12L, "Dacia" },
                    { 13L, "Daewoo" },
                    { 14L, "Daihatsu" },
                    { 15L, "Dodge" },
                    { 16L, "Donkervoort" },
                    { 17L, "DS" },
                    { 18L, "Ferrari" },
                    { 19L, "Fiat" },
                    { 20L, "Fisker" },
                    { 21L, "Ford" },
                    { 22L, "Honda" },
                    { 23L, "Hummer" },
                    { 24L, "Hyundai" },
                    { 25L, "Infiniti" },
                    { 26L, "Iveco" },
                    { 27L, "Jaguar" },
                    { 28L, "Jeep" },
                    { 29L, "Kia" },
                    { 30L, "KTM" },
                    { 31L, "Lada" },
                    { 32L, "Lamborghini" },
                    { 33L, "Lancia" },
                    { 34L, "Land Rover" },
                    { 35L, "Landwind" },
                    { 36L, "Lexus" },
                    { 37L, "Lotus" },
                    { 38L, "Maserati" },
                    { 39L, "Maybach" },
                    { 40L, "Mazda" },
                    { 41L, "McLaren" },
                    { 42L, "Mercedes-Benz" },
                    { 43L, "MG" },
                    { 44L, "Mini" },
                    { 45L, "Mitsubishi" },
                    { 46L, "Morgan" },
                    { 47L, "Nissan" },
                    { 48L, "Opel" },
                    { 49L, "Peugeot" },
                    { 50L, "Porsche" },
                    { 51L, "Renault" },
                    { 52L, "Rolls-Royce" },
                    { 53L, "Rover" },
                    { 54L, "Saab" },
                    { 55L, "Seat" },
                    { 56L, "Skoda" },
                    { 57L, "Smart" },
                    { 58L, "SsangYong" },
                    { 59L, "Subaru" },
                    { 60L, "Suzuki" },
                    { 61L, "Tesla" },
                    { 62L, "Toyota" },
                    { 63L, "Volkswagen" },
                    { 64L, "Volvo" }
                });

            migrationBuilder.InsertData(
                table: "CarModelYear",
                columns: new[] { "ID", "Description" },
                values: new object[,]
                {
                    { 1L, "Accent" },
                    { 2L, "Atos" },
                    { 3L, "Prime" },
                    { 4L, "Coupé" },
                    { 5L, "Elantra" },
                    { 6L, "Galloper" },
                    { 7L, "Genesis" },
                    { 8L, "Getz" },
                    { 9L, "Grandeur" },
                    { 10L, "H350" },
                    { 11L, "H1" },
                    { 12L, "H1Bus" },
                    { 13L, "H1Van" },
                    { 14L, "H200" },
                    { 15L, "i10" },
                    { 16L, "i20" },
                    { 17L, "i30" },
                    { 18L, "i30 CW" },
                    { 19L, "i40" },
                    { 20L, "i40 CW" },
                    { 21L, "ix20" },
                    { 22L, "ix35" },
                    { 23L, "ix55" },
                    { 24L, "Lantra" },
                    { 25L, "Matrix" },
                    { 26L, "SantaFe" },
                    { 27L, "Sonata" },
                    { 28L, "Terracan" },
                    { 29L, "Trajet" },
                    { 30L, "Tucson" },
                    { 31L, "Veloster" },
                    { 32L, "Kona" },
                    { 33L, "Tucson" },
                    { 34L, "Bayon" },
                    { 35L, "145" },
                    { 36L, "146" },
                    { 37L, "147" },
                    { 38L, "155" },
                    { 39L, "156" },
                    { 40L, "156 Sportwagon" },
                    { 41L, "159" },
                    { 42L, "159 Sportwagon" },
                    { 43L, "164" },
                    { 44L, "166" },
                    { 45L, "4C" },
                    { 46L, "Brera" },
                    { 47L, "GTV" },
                    { 48L, "MiTo" },
                    { 49L, "Crosswagon" },
                    { 50L, "Spider" },
                    { 51L, "GT" },
                    { 52L, "Giulietta" },
                    { 53L, "Giulia" },
                    { 54L, "4-Runner"},
                    { 55L, "Auris"},
                    { 56L, "Avensis"},
                    { 57L, "Avensis Combi"},
                    { 58L, "Avensis Van Verso"},
                    { 59L, "Aygo"},
                    { 60L, "Camry"},
                    { 61L, "Carina"},
                    { 62L, "Celica"},
                    { 63L, "Corolla"},
                    { 64L, "Corolla Combi"},
                    { 65L, "Corolla sedan"},
                    { 66L, "Corolla Verso"},
                    { 67L, "FJ Cruiser"},
                    { 68L, "GT86"},
                    { 69L, "Hiace"},
                    { 70L, "Hiace Van"},
                    { 71L, "Highlander"},
                    { 72L, "Hilux"},
                    { 73L, "Land Cruiser"},
                    { 74L, "MR2"},
                    { 75L, "Paseo"},
                    { 76L, "Picnic"},
                    { 77L, "Prius"},
                    { 78L, "RAV4"},
                    { 79L, "Sequoia"},
                    { 80L, "Starlet"},
                    { 81L, "Supra"},
                    { 82L, "Tundra"},
                    { 83L, "Urban Cruiser"},
                    { 84L, "Verso"},
                    { 85L, "Yaris"},
                    { 86L, "Yaris Verso"},
                    { 87L, "Alhambra,"},
                    { 88L, "Altea"},
                    { 89L, "Altea XL"},
                    { 90L, "Arosa"},
                    { 91L, "Cordoba"},
                    { 92L, "Cordoba Vario"},
                    { 93L, "Exeo"},
                    { 94L, "Ibiza,"},
                    { 95L, "Ibiza ST"},
                    { 96L, "Exeo ST"},
                    { 97L, "Leon,"},
                    { 98L, "Leon ST"},
                    { 99L, "Inca"},
                    { 100L, "Mii,"},
                    { 101L, "Toledo"},
                    { 102L, "Captur"},
                    { 103L, "Clio"},
                    { 104L, "Clio Grandtour"},
                    { 105L, "Espace"},
                    { 106L, "Express"},
                    { 107L, "Fluence"},
                    { 108L, "Grand Espace"},
                    { 109L, "Grand Modus"},
                    { 110L, "Grand Scenic"},
                    { 111L, "Kadjar"},
                    { 112L, "Kangoo"},
                    { 113L, "Kangoo Express"},
                    { 114L, "Koleos"},
                    { 115L, "Laguna"},
                    { 116L, "Laguna Grandtour"},
                    { 117L, "Latitude"},
                    { 118L, "Mascott"},
                    { 119L, "Mégane"},
                    { 120L, "Mégane CC"},
                    { 121L, "Mégane Combi"},
                    { 122L, "Mégane Grandtour"},
                    { 123L, "Mégane Coupé"},
                    { 124L, "Mégane Scénic"},
                    { 125L, "Scénic"},
                    { 126L, "Talisman"},
                    { 127L, "Talisman Grandtour"},
                    { 128L, "Thalia"},
                    { 129L, "Twingo"},
                    { 130L, "Wind"},
                    { 131L, "Zoé"},
                    { 132L, "1007"},
                    { 133L, "107"},
                    { 134L, "106"},
                    { 135L, "108"},
                    { 136L, "2008"},
                    { 137L, "205"},
                    { 138L, "205 Cabrio"},
                    { 139L, "206"},
                    { 140L, "206 CC"},
                    { 141L, "206 SW"},
                    { 142L, "207"},
                    { 143L, "207 CC"},
                    { 144L, "207 SW"},
                    { 145L, "306"},
                    { 146L, "307"},
                    { 147L, "307 CC"},
                    { 148L, "307 SW"},
                    { 149L, "308"},
                    { 150L, "308 CC"},
                    { 151L, "308 SW"},
                    { 152L, "309"},
                    { 153L, "4007"},
                    { 154L, "4008"},
                    { 155L, "405"},
                    { 156L, "406"},
                    { 157L, "407"},
                    { 158L, "407 SW"},
                    { 159L, "5008"},
                    { 160L, "508"},
                    { 161L, "508 SW"},
                    { 162L, "605"},
                    { 163L, "806"},
                    { 164L, "607"},
                    { 165L, "807"},
                    { 166L, "Bipper"},
                    { 167L, "RCZ Dokker"},
                    { 168L, "Duster"},
                    { 169L, "Lodgy"},
                    { 170L, "Logan"},
                    { 171L, "Logan MCV"},
                    { 172L, "Logan Van"},
                    { 173L, "Sandero"},
                    { 174L, "Solenza Berlingo"},
                    { 175L, "C-Crosser"},
                    { 176L, "C-Elissée"},
                    { 177L, "C-Zero"},
                    { 178L, "C1"},
                    { 179L, "C2"},
                    { 180L, "C3"},
                    { 181L, "C3 Picasso"},
                    { 182L, "C4"},
                    { 183L, "C4 Aircross"},
                    { 184L, "C4 Cactus"},
                    { 185L, "C4 Coupé"},
                    { 186L, "C4 Grand Picasso"},
                    { 187L, "C4 Sedan"},
                    { 188L, "C5"},
                    { 189L, "C5 Break"},
                    { 190L, "C5 Tourer"},
                    { 191L, "C6"},
                    { 192L, "C8"},
                    { 193L, "DS3"},
                    { 194L, "DS4"},
                    { 195L, "DS5"},
                    { 196L, "Evasion"},
                    { 197L, "Jumper"},
                    { 198L, "Jumpy"},
                    { 199L, "Saxo"},
                    { 200L, "Nemo"},
                    { 201L, "Xantia"},
                    { 202L, "Xsara Agila"},
                    { 203L, "Ampera"},
                    { 204L, "Antara"},
                    { 205L, "Astra"},
                    { 206L, "Astra cabrio"},
                    { 207L, "Astra caravan"},
                    { 208L, "Astra coupé"},
                    { 209L, "Calibra"},
                    { 210L, "Campo"},
                    { 211L, "Cascada"},
                    { 212L, "Corsa"},
                    { 213L, "Frontera"},
                    { 214L, "Insignia"},
                    { 215L, "Insignia kombi"},
                    { 216L, "Kadett"},
                    { 217L, "Meriva"},
                    { 218L, "Mokka"},
                    { 219L, "Movano"},
                    { 220L, "Omega"},
                    { 221L, "Signum"},
                    { 222L, "Vectra"},
                    { 223L, "Vectra Caravan"},
                    { 224L, "Vivaro"},
                    { 225L, "Vivaro Kombi"},
                    { 226L, "Zafira"},
                    { 227L, "Favorit"},
                    { 228L, "Felicia"},
                    { 229L, "Citigo"},
                    { 230L, "Fabia"},
                    { 231L, "Fabia Combi"},
                    { 232L, "Fabia Sedan"},
                    { 233L, "Felicia Combi"},
                    { 234L, "Octavia"},
                    { 235L, "Octavia Combi"},
                    { 236L, "Roomster"},
                    { 237L, "Yeti"},
                    { 238L, "Rapid"},
                    { 239L, "Rapid Spaceback"},
                    { 240L, "Superb"},
                    { 241L, "Superb Combi"},
                    { 242L, "Alero"},
                    { 243L, "Aveo"},
                    { 244L, "Camaro"},
                    { 245L, "Captiva"},
                    { 246L, "Corvette"},
                    { 247L, "Cruze"},
                    { 248L, "Cruze SW"},
                    { 249L, "Epica"},
                    { 250L, "Equinox"},
                    { 251L, "Evanda"},
                    { 252L, "HHR"},
                    { 253L, "Kalos"},
                    { 254L, "Lacetti"},
                    { 255L, "Lacetti SW"},
                    { 256L, "Lumina"},
                    { 257L, "Malibu"},
                    { 258L, "Matiz"},
                    { 259L, "Monte Carlo"},
                    { 260L, "Nubira"},
                    { 261L, "Orlando"},
                    { 262L, "Spark"},
                    { 263L, "Suburban"},
                    { 264L, "Tacuma"},
                    { 265L, "Tahoe"},
                    { 266L, "Trax"},
                    { 267L, "911 Carrera"},
                    { 268L, "911 Carrera Cabrio"},
                    { 269L, "911 Targa"},
                    { 270L, "911 Turbo"},
                    { 271L, "924"},
                    { 272L, "944"},
                    { 273L, "997"},
                    { 274L, "Boxster"},
                    { 275L, "Cayenne"},
                    { 276L, "Cayman"},
                    { 277L, "Macan"},
                    { 278L, "Panamera"},
                    { 279L, "Accord"},
                    { 280L, "Accord Coupé"},
                    { 281L, "Accord Tourer"},
                    { 282L, "City"},
                    { 283L, "Civic"},
                    { 284L, "Civic Aerodeck"},
                    { 285L, "Civic Coupé"},
                    { 286L, "Civic Tourer"},
                    { 287L, "Civic Type R"},
                    { 288L, "CR-V"},
                    { 289L, "CR-X"},
                    { 290L, "CR-Z"},
                    { 291L, "FR-V"},
                    { 292L, "HR-V"},
                    { 293L, "Insight"},
                    { 294L, "Integra"},
                    { 295L, "Jazz"},
                    { 296L, "Legend"},
                    { 297L, "Prelude"},
                    { 298L, "BRZ"},
                    { 299L, "Forester"},
                    { 300L, "Impreza"},
                    { 301L, "Impreza Wagon"},
                    { 302L, "Justy"},
                    { 303L, "Legacy"},
                    { 304L, "Legacy Wagon"},
                    { 305L, "Legacy Outback"},
                    { 306L, "Levorg"},
                    { 307L, "Outback"},
                    { 308L, "SVX"},
                    { 309L, "Tribeca"},
                    { 310L, "Tribeca B9"},
                    { 311L, "XV"},
                    { 312L, "121"},
                    { 313L, "2"},
                    { 314L, "3"},
                    { 315L, "323"},
                    { 316L, "323 Combi"},
                    { 317L, "323 Coupé"},
                    { 318L, "323 F"},
                    { 319L, "5"},
                    { 320L, "6"},
                    { 321L, "6 Combi"},
                    { 322L, "626"},
                    { 323L, "626 Combi"},
                    { 324L, "B-Fighter"},
                    { 325L, "B2500"},
                    { 326L, "BT"},
                    { 327L, "CX-3"},
                    { 328L, "CX-5"},
                    { 329L, "CX-7"},
                    { 330L, "CX-9"},
                    { 331L, "Demio"},
                    { 332L, "MPV"},
                    { 333L, "MX-3"},
                    { 334L, "MX-5"},
                    { 335L, "MX-6"},
                    { 336L, "Premacy"},
                    { 337L, "RX-7"},
                    { 338L, "RX-8"},
                    { 339L, "Xedox 6"},
                    { 340L, "3000 GT"},
                    { 341L, "ASX"},
                    { 342L, "Carisma"},
                    { 343L, "Colt"},
                    { 344L, "Colt CC"},
                    { 345L, "Eclipse"},
                    { 346L, "Fuso canter"},
                    { 347L, "Galant"},
                    { 348L, "Galant Combi"},
                    { 349L, "Grandis"},
                    { 350L, "L200"},
                    { 351L, "L200 Pick up"},
                    { 352L, "L200 Pick up Allrad"},
                    { 353L, "L300"},
                    { 354L, "Lancer"},
                    { 355L, "Lancer Combi"},
                    { 356L, "Lancer Evo"},
                    { 357L, "Lancer Sportback"},
                    { 358L, "Outlander"},
                    { 359L, "Pajero"},
                    { 360L, "Pajeto Pinin"},
                    { 361L, "Pajero Pinin Wagon"},
                    { 362L, "Pajero Sport"},
                    { 363L, "Pajero Wagon"},
                    { 364L, "Space Star"},
                    { 365L, "CT"},
                    { 366L, "GS"},
                    { 367L, "GS 300"},
                    { 368L, "GX"},
                    { 369L, "IS"},
                    { 370L, "IS 200"},
                    { 371L, "IS 250 C"},
                    { 372L, "IS-F"},
                    { 373L, "LS"},
                    { 374L, "LX"},
                    { 375L, "NX"},
                    { 376L, "RC F"},
                    { 377L, "RX"},
                    { 378L, "RX 300"},
                    { 379L, "RX 400h"},
                    { 380L, "RX 450h"},
                    { 381L, "SC 430"},
                    { 382L, "i3"},
                    { 383L, "i8"},
                    { 384L, "M3"},
                    { 385L, "M4"},
                    { 386L, "M5"},
                    { 387L, "M6"},
                    { 388L, "Rad 1"},
                    { 389L, "Rad 1 Cabrio"},
                    { 390L, "Rad 1 Coupé"},
                    { 391L, "Rad 2"},
                    { 392L, "Rad 2 Active Tourer"},
                    { 393L, "Rad 2 Coupé"},
                    { 394L, "Rad 2 Gran Tourer"},
                    { 395L, "Rad 3"},
                    { 396L, "Rad 3 Cabrio"},
                    { 397L, "Rad 3 Compact"},
                    { 398L, "Rad 3 Coupé"},
                    { 399L, "Rad 3 GT"},
                    { 400L, "Rad 3 Touring"},
                    { 401L, "Rad 4"},
                    { 402L, "Rad 4 Cabrio"},
                    { 403L, "Rad 4 Gran Coupé"},
                    { 404L, "Rad 5"},
                    { 405L, "Rad 5 GT"},
                    { 406L, "Rad 5 Touring"},
                    { 407L, "Rad 6"},
                    { 408L, "Rad 6 Cabrio"},
                    { 409L, "Rad 6 Coupé"},
                    { 410L, "Rad 6 Gran Coupé"},
                    { 411L, "Rad 7"},
                    { 412L, "Rad 8 Coupé"},
                    { 413L, "X1"},
                    { 414L, "X3"},
                    { 415L, "X4"},
                    { 416L, "X5"},
                    { 417L, "X6"},
                    { 418L, "Z3"},
                    { 419L, "Z3 Coupé"},
                    { 420L, "Z3 Roadster"},
                    { 421L, "Z4"},
                    { 422L, "Z4 Roadster"},
                    { 423L, "Amarok"},
                    { 424L, "Beetle"},
                    { 425L, "Bora"},
                    { 426L, "Bora Variant"},
                    { 427L, "Caddy"},
                    { 428L, "Caddy Van"},
                    { 429L, "Life"},
                    { 430L, "California"},
                    { 431L, "Caravelle"},
                    { 432L, "CC"},
                    { 433L, "Crafter"},
                    { 434L, "Crafter Van"},
                    { 435L, "Crafter Kombi"},
                    { 436L, "CrossTouran"},
                    { 437L, "Eos"},
                    { 438L, "Fox"},
                    { 439L, "Golf"},
                    { 440L, "Golf Cabrio"},
                    { 441L, "Golf Plus"},
                    { 442L, "Golf Sportvan"},
                    { 443L, "Golf Variant"},
                    { 444L, "Jetta"},
                    { 445L, "LT"},
                    { 446L, "Lupo"},
                    { 447L, "Multivan"},
                    { 448L, "New Beetle"},
                    { 449L, "New Beetle Cabrio"},
                    { 450L, "Passat"},
                    { 451L, "Passat Alltrack"},
                    { 452L, "Passat CC"},
                    { 453L, "Passat Variant"},
                    { 454L, "Passat Variant Van"},
                    { 455L, "Phaeton"},
                    { 456L, "Polo"},
                    { 457L, "Polo Van"},
                    { 458L, "Polo Variant"},
                    { 459L, "Scirocco"},
                    { 460L, "Sharan"},
                    { 461L, "T4"},
                    { 462L, "T4 Caravelle"},
                    { 463L, "T4 Multivan"},
                    { 464L, "T5"},
                    { 465L, "T5 Caravelle"},
                    { 466L, "T5 Multivan"},
                    { 467L, "T5 Transporter Shuttle"},
                    { 468L, "Tiguan"},
                    { 469L, "Touareg"},
                    { 470L, "Touran"},
                    { 471L, "Alto"},
                    { 472L, "Baleno"},
                    { 473L, "Baleno kombi"},
                    { 474L, "Grand Vitara"},
                    { 475L, "Grand Vitara XL-7"},
                    { 476L, "Ignis"},
                    { 477L, "Jimny"},
                    { 478L, "Kizashi"},
                    { 479L, "Liana"},
                    { 480L, "Samurai"},
                    { 481L, "Splash"},
                    { 482L, "Swift"},
                    { 483L, "SX4"},
                    { 484L, "SX4 Sedan"},
                    { 485L, "Vitara"},
                    { 486L, "Wagon R+"},
                    { 487L, "100 D"},
                    { 488L, "115"},
                    { 489L, "124"},
                    { 490L, "126"},
                    { 491L, "190"},
                    { 492L, "190 D"},
                    { 493L, "190 E"},
                    { 494L, "200 - 300"},
                    { 495L, "200 D"},
                    { 496L, "200 E"},
                    { 497L, "210 Van"},
                    { 498L, "210 kombi"},
                    { 499L, "310 Van"},
                    { 500L, "310 kombi"},
                    { 501L, "230 - 300 CE Coupé"},
                    { 502L, "260 - 560 SE"},
                    { 503L, "260 - 560 SEL"},
                    { 504L, "500 - 600 SEC Coupé"},
                    { 505L, "Trieda A"},
                    { 506L, "A"},
                    { 507L, "A L"},
                    { 508L, "AMG GT"},
                    { 509L, "Trieda B"},
                    { 510L, "Trieda C"},
                    { 511L, "C"},
                    { 512L, "C Sportcoupé"},
                    { 513L, "C T"},
                    { 514L, "Citan"},
                    { 515L, "CL"},
                    { 516L, "CL"},
                    { 517L, "CLA"},
                    { 518L, "CLC"},
                    { 519L, "CLK Cabrio"},
                    { 520L, "CLK Coupé"},
                    { 521L, "CLS"},
                    { 522L, "Trieda E"},
                    { 523L, "E"},
                    { 524L, "E Cabrio"},
                    { 525L, "E Coupé"},
                    { 526L, "E T"},
                    { 527L, "Trieda G"},
                    { 528L, "G Cabrio"},
                    { 529L, "GL"},
                    { 530L, "GLA"},
                    { 531L, "GLC"},
                    { 532L, "GLE"},
                    { 533L, "GLK"},
                    { 534L, "Trieda M"},
                    { 535L, "MB 100"},
                    { 536L, "Trieda R"},
                    { 537L, "Trieda S"},
                    { 538L, "S"},
                    { 539L, "S Coupé"},
                    { 540L, "SL"},
                    { 541L, "SLC"},
                    { 542L, "SLK"},
                    { 543L, "SLR"},
                    { 544L, "Sprinter"},
                    { 545L, "44994"},
                    { 546L, "9-3 Cabriolet"},
                    { 547L, "9-3 Coupé"},
                    { 548L, "9-3 SportCombi"},
                    { 549L, "45055"},
                    { 550L, "9-5 SportCombi"},
                    { 551L, "900"},
                    { 552L, "900 C"},
                    { 553L, "900 C Turbo"},
                    { 554L, "9000"},
                    { 555L, "100"},
                    { 556L, "100 Avant"},
                    { 557L, "80"},
                    { 558L, "80 Avant"},
                    { 559L, "80 Cabrio"},
                    { 560L, "90"},
                    { 561L, "A1"},
                    { 562L, "A2"},
                    { 563L, "A3"},
                    { 564L, "A3 Cabriolet"},
                    { 565L, "A3 Limuzina"},
                    { 566L, "A3 Sportback"},
                    { 567L, "A4"},
                    { 568L, "A4 Allroad"},
                    { 569L, "A4 Avant"},
                    { 570L, "A4 Cabriolet"},
                    { 571L, "A5"},
                    { 572L, "A5 Cabriolet"},
                    { 573L, "A5 Sportback"},
                    { 574L, "A6"},
                    { 575L, "A6 Allroad"},
                    { 576L, "A6 Avant"},
                    { 577L, "A7"},
                    { 578L, "A8"},
                    { 579L, "A8 Long"},
                    { 580L, "Q3"},
                    { 581L, "Q5"},
                    { 582L, "Q7"},
                    { 583L, "R8"},
                    { 584L, "RS4 Cabriolet"},
                    { 585L, "RS4/RS4 Avant"},
                    { 586L, "RS5"},
                    { 587L, "RS6 Avant"},
                    { 588L, "RS7"},
                    { 589L, "S3/S3 Sportback"},
                    { 590L, "S4 Cabriolet"},
                    { 591L, "S4/S4 Avant"},
                    { 592L, "S5/S5 Cabriolet"},
                    { 593L, "S6/RS6"},
                    { 594L, "S7"},
                    { 595L, "S8"},
                    { 596L, "SQ5"},
                    { 597L, "TT Coupé"},
                    { 598L, "TT Roadster"},
                    { 599L, "TTS"},
                    { 600L, "Avella"},
                    { 601L, "Besta"},
                    { 602L, "Carens"},
                    { 603L, "Carnival"},
                    { 604L, "Cee`d"},
                    { 605L, "Cee`d SW"},
                    { 606L, "Cerato"},
                    { 607L, "K 2500"},
                    { 608L, "Magentis"},
                    { 609L, "Opirus"},
                    { 610L, "Optima"},
                    { 611L, "Picanto"},
                    { 612L, "Pregio"},
                    { 613L, "Pride"},
                    { 614L, "Pro Cee`d"},
                    { 615L, "Rio"},
                    { 616L, "Rio Combi"},
                    { 617L, "Rio sedan"},
                    { 618L, "Sephia"},
                    { 619L, "Shuma"},
                    { 620L, "Sorento"},
                    { 621L, "Soul"},
                    { 622L, "Sportage"},
                    { 623L, "Venga"},
                    { 624L, "109"},
                    { 625L, "Defender"},
                    { 626L, "Discovery"},
                    { 627L, "Discovery Sport"},
                    { 628L, "Freelander"},
                    { 629L, "Range Rover"},
                    { 630L, "Range Rover Evoque"},
                    { 631L, "Range Rover Sport"},
                    { 632L, "Avenger"},
                    { 633L, "Caliber"},
                    { 634L, "Challenger"},
                    { 635L, "Charger"},
                    { 636L, "Grand Caravan"},
                    { 637L, "Journey"},
                    { 638L, "Magnum"},
                    { 639L, "Nitro"},
                    { 640L, "RAM"},
                    { 641L, "Stealth"},
                    { 642L, "Viper"},
                    { 643L, "300 C"},
                    { 644L, "300 C Touring"},
                    { 645L, "300 M"},
                    { 646L, "Crossfire"},
                    { 647L, "Grand Voyager"},
                    { 648L, "LHS"},
                    { 649L, "Neon"},
                    { 650L, "Pacifica"},
                    { 651L, "Plymouth"},
                    { 652L, "PT Cruiser"},
                    { 653L, "Sebring"},
                    { 654L, "Sebring Convertible"},
                    { 655L, "Stratus"},
                    { 656L, "Stratus Cabrio"},
                    { 657L, "Town & Country"},
                    { 658L, "Voyager"},
                    { 659L, "Aerostar"},
                    { 660L, "B-Max"},
                    { 661L, "C-Max"},
                    { 662L, "Cortina"},
                    { 663L, "Cougar"},
                    { 664L, "Edge"},
                    { 665L, "Escort"},
                    { 666L, "Escort Cabrio"},
                    { 667L, "Escort kombi"},
                    { 668L, "Explorer"},
                    { 669L, "F-150"},
                    { 670L, "F-250"},
                    { 671L, "Fiesta"},
                    { 672L, "Focus"},
                    { 673L, "Focus C-Max"},
                    { 674L, "Focus CC"},
                    { 675L, "Focus kombi"},
                    { 676L, "Fusion"},
                    { 677L, "Galaxy"},
                    { 678L, "Grand C-Max"},
                    { 679L, "Ka"},
                    { 680L, "Kuga"},
                    { 681L, "Maverick"},
                    { 682L, "Mondeo"},
                    { 683L, "Mondeo Combi"},
                    { 684L, "Mustang"},
                    { 685L, "Orion"},
                    { 686L, "Puma"},
                    { 687L, "Ranger"},
                    { 688L, "S-Max"},
                    { 689L, "Sierra"},
                    { 690L, "Street Ka"},
                    { 691L, "Tourneo Connect"},
                    { 692L, "Tourneo Custom"},
                    { 693L, "Transit"},
                    { 694L, "Transit"},
                    { 695L, "Transit Bus"},
                    { 696L, "Transit Connect LWB"},
                    { 697L, "Transit Courier"},
                    { 698L, "Transit Custom"},
                    { 699L, "Transit kombi"},
                    { 700L, "Transit Tourneo"},
                    { 701L, "Transit Valnik"},
                    { 702L, "Transit Van"},
                    { 703L, "Transit Van 350"},
                    { 704L, "Windstar"},
                    { 705L, "H2"},
                    { 706L, "H3"},
                    { 707L, "EX"},
                    { 708L, "FX"},
                    { 709L, "G"},
                    { 710L, "G Coupé"},
                    { 711L, "M"},
                    { 712L, "Q"},
                    { 713L, "QX"},
                    { 714L, "Daimler"},
                    { 715L, "F-Pace"},
                    { 716L, "F-Type"},
                    { 717L, "S-Type"},
                    { 718L, "Sovereign"},
                    { 719L, "X-Type"},
                    { 720L, "X-type Estate"},
                    { 721L, "XE"},
                    { 722L, "XF"},
                    { 723L, "XJ"},
                    { 724L, "XJ12"},
                    { 725L, "XJ6"},
                    { 726L, "XJ8"},
                    { 727L, "XJ8"},
                    { 728L, "XJR"},
                    { 729L, "XK"},
                    { 730L, "XK8 Convertible"},
                    { 731L, "XKR"},
                    { 732L, "XKR Convertible"},
                    { 733L, "Cherokee"},
                    { 734L, "Commander"},
                    { 735L, "Compass"},
                    { 736L, "Grand Cherokee"},
                    { 737L, "Patriot"},
                    { 738L, "Renegade"},
                    { 739L, "Wrangler"},
                    { 740L, "100 NX"},
                    { 741L, "200 SX"},
                    { 742L, "350 Z"},
                    { 743L, "350 Z Roadster"},
                    { 744L, "370 Z"},
                    { 745L, "Almera"},
                    { 746L, "Almera Tino"},
                    { 747L, "Cabstar E - T"},
                    { 748L, "Cabstar TL2 Valnik"},
                    { 749L, "e-NV200"},
                    { 750L, "GT-R"},
                    { 751L, "Insterstar"},
                    { 752L, "Juke"},
                    { 753L, "King Cab"},
                    { 754L, "Leaf"},
                    { 755L, "Maxima"},
                    { 756L, "Maxima QX"},
                    { 757L, "Micra"},
                    { 758L, "Murano"},
                    { 759L, "Navara"},
                    { 760L, "Note"},
                    { 761L, "NP300 Pickup"},
                    { 762L, "NV200"},
                    { 763L, "NV400"},
                    { 764L, "Pathfinder"},
                    { 765L, "Patrol"},
                    { 766L, "Patrol GR"},
                    { 767L, "Pickup"},
                    { 768L, "Pixo"},
                    { 769L, "Primastar"},
                    { 770L, "Primastar Combi"},
                    { 771L, "Primera"},
                    { 772L, "Primera Combi"},
                    { 773L, "Pulsar"},
                    { 774L, "Qashqai"},
                    { 775L, "Serena"},
                    { 776L, "Sunny"},
                    { 777L, "Terrano"},
                    { 778L, "Tiida"},
                    { 779L, "Trade"},
                    { 780L, "Vanette Cargo"},
                    { 781L, "X-Trail"},
                    { 782L, "240"},
                    { 783L, "340"},
                    { 784L, "360"},
                    { 785L, "460"},
                    { 786L, "850"},
                    { 787L, "850 kombi"},
                    { 788L, "C30"},
                    { 789L, "C70"},
                    { 790L, "C70 Cabrio"},
                    { 791L, "C70 Coupé"},
                    { 792L, "S40"},
                    { 793L, "S60"},
                    { 794L, "S70"},
                    { 795L, "S80"},
                    { 796L, "S90"},
                    { 797L, "V40"},
                    { 798L, "V50"},
                    { 799L, "V60"},
                    { 800L, "V70"},
                    { 801L, "V90"},
                    { 802L, "XC60"},
                    { 803L, "XC70"},
                    { 804L, "XC90"},
                    { 805L, "Espero"},
                    { 806L, "Kalos"},
                    { 807L, "Lacetti"},
                    { 808L, "Lanos"},
                    { 809L, "Leganza"},
                    { 810L, "Lublin"},
                    { 811L, "Matiz"},
                    { 812L, "Nexia"},
                    { 813L, "Nubira"},
                    { 814L, "Nubira kombi"},
                    { 815L, "Racer"},
                    { 816L, "Tacuma"},
                    { 817L, "Tico"},
                    { 818L, "1100"},
                    { 819L, "126"},
                    { 820L, "500"},
                    { 821L, "500L"},
                    { 822L, "500X"},
                    { 823L, "850"},
                    { 824L, "Barchetta"},
                    { 825L, "Brava"},
                    { 826L, "Cinquecento"},
                    { 827L, "Coupé"},
                    { 828L, "Croma"},
                    { 829L, "Doblo"},
                    { 830L, "Doblo Cargo"},
                    { 831L, "Doblo Cargo Combi"},
                    { 832L, "Ducato"},
                    { 833L, "Ducato Van"},
                    { 834L, "Ducato Kombi"},
                    { 835L, "Ducato Podvozok"},
                    { 836L, "Florino"},
                    { 837L, "Florino Combi"},
                    { 838L, "Freemont"},
                    { 839L, "Grande Punto"},
                    { 840L, "Idea"},
                    { 841L, "Linea"},
                    { 842L, "Marea"},
                    { 843L, "Marea Weekend"},
                    { 844L, "Multipla"},
                    { 845L, "Palio Weekend"},
                    { 846L, "Panda"},
                    { 847L, "Panda Van"},
                    { 848L, "Punto"},
                    { 849L, "Punto Cabriolet"},
                    { 850L, "Punto Evo"},
                    { 851L, "Punto Van"},
                    { 852L, "Qubo"},
                    { 853L, "Scudo"},
                    { 854L, "Scudo Van"},
                    { 855L, "Scudo Kombi"},
                    { 856L, "Sedici"},
                    { 857L, "Seicento"},
                    { 858L, "Stilo"},
                    { 859L, "Stilo Multiwagon"},
                    { 860L, "Strada"},
                    { 861L, "Talento"},
                    { 862L, "Tipo"},
                    { 863L, "Ulysse"},
                    { 864L, "Uno"},
                    { 865L, "X1/9"},
                    { 866L, "Cooper"},
                    { 867L, "Cooper Cabrio"},
                    { 868L, "Cooper Clubman"},
                    { 869L, "Cooper D"},
                    { 870L, "Cooper D Clubman"},
                    { 871L, "Cooper S"},
                    { 872L, "Cooper S Cabrio"},
                    { 873L, "Cooper S Clubman"},
                    { 874L, "Countryman"},
                    { 875L, "Mini One"},
                    { 876L, "One D"},
                    { 877L, "200"},
                    { 878L, "214"},
                    { 879L, "218"},
                    { 880L, "25"},
                    { 881L, "400"},
                    { 882L, "414"},
                    { 883L, "416"},
                    { 884L, "620"},
                    { 885L, "75"},
                    { 886L, "Cabrio"},
                    { 887L, "City-Coupé"},
                    { 888L, "Compact Pulse"},
                    { 889L, "Forfour"},
                    { 890L, "Fortwo cabrio"},
                    { 891L, "Fortwo coupé"},
                    { 892L, "Roadster"}

                });

            migrationBuilder.InsertData(
                table: "CarModels",
                columns: new[] { "ID", "ModelName" },
                values: new object[,]
                {
                    { 1L, "Accent" },
                    { 2L, "Atos" },
                    { 3L, "Prime" },
                    { 4L, "Coupé" },
                    { 5L, "Elantra" },
                    { 6L, "Galloper" },
                    { 7L, "Genesis" },
                    { 8L, "Getz" },
                    { 9L, "Grandeur" },
                    { 10L, "H350" },
                    { 11L, "H1" },
                    { 12L, "H1Bus" },
                    { 13L, "H1Van" },
                    { 14L, "H200" },
                    { 15L, "i10" },
                    { 16L, "i20" },
                    { 17L, "i30" },
                    { 18L, "i30 CW" },
                    { 19L, "i40" },
                    { 20L, "i40 CW" },
                    { 21L, "ix20" },
                    { 22L, "ix35" },
                    { 23L, "ix55" },
                    { 24L, "Lantra" },
                    { 25L, "Matrix" },
                    { 26L, "SantaFe" },
                    { 27L, "Sonata" },
                    { 28L, "Terracan" },
                    { 29L, "Trajet" },
                    { 30L, "Tucson" },
                    { 31L, "Veloster" },
                    { 32L, "Kona" },
                    { 33L, "Tucson" },
                    { 34L, "Bayon" },
                    { 35L, "145" },
                    { 36L, "146" },
                    { 37L, "147" },
                    { 38L, "155" },
                    { 39L, "156" },
                    { 40L, "156 Sportwagon" },
                    { 41L, "159" },
                    { 42L, "159 Sportwagon" },
                    { 43L, "164" },
                    { 44L, "166" },
                    { 45L, "4C" },
                    { 46L, "Brera" },
                    { 47L, "GTV" },
                    { 48L, "MiTo" },
                    { 49L, "Crosswagon" },
                    { 50L, "Spider" },
                    { 51L, "GT" },
                    { 52L, "Giulietta" },
                    { 53L, "Giulia" },
                    { 54L, "4-Runner"},
                    { 55L, "Auris"},
                    { 56L, "Avensis"},
                    { 57L, "Avensis Combi"},
                    { 58L, "Avensis Van Verso"},
                    { 59L, "Aygo"},
                    { 60L, "Camry"},
                    { 61L, "Carina"},
                    { 62L, "Celica"},
                    { 63L, "Corolla"},
                    { 64L, "Corolla Combi"},
                    { 65L, "Corolla sedan"},
                    { 66L, "Corolla Verso"},
                    { 67L, "FJ Cruiser"},
                    { 68L, "GT86"},
                    { 69L, "Hiace"},
                    { 70L, "Hiace Van"},
                    { 71L, "Highlander"},
                    { 72L, "Hilux"},
                    { 73L, "Land Cruiser"},
                    { 74L, "MR2"},
                    { 75L, "Paseo"},
                    { 76L, "Picnic"},
                    { 77L, "Prius"},
                    { 78L, "RAV4"},
                    { 79L, "Sequoia"},
                    { 80L, "Starlet"},
                    { 81L, "Supra"},
                    { 82L, "Tundra"},
                    { 83L, "Urban Cruiser"},
                    { 84L, "Verso"},
                    { 85L, "Yaris"},
                    { 86L, "Yaris Verso"},
                    { 87L, "Alhambra,"},
                    { 88L, "Altea"},
                    { 89L, "Altea XL"},
                    { 90L, "Arosa"},
                    { 91L, "Cordoba"},
                    { 92L, "Cordoba Vario"},
                    { 93L, "Exeo"},
                    { 94L, "Ibiza,"},
                    { 95L, "Ibiza ST"},
                    { 96L, "Exeo ST"},
                    { 97L, "Leon,"},
                    { 98L, "Leon ST"},
                    { 99L, "Inca"},
                    { 100L, "Mii,"},
                    { 101L, "Toledo"},
                    { 102L, "Captur"},
                    { 103L, "Clio"},
                    { 104L, "Clio Grandtour"},
                    { 105L, "Espace"},
                    { 106L, "Express"},
                    { 107L, "Fluence"},
                    { 108L, "Grand Espace"},
                    { 109L, "Grand Modus"},
                    { 110L, "Grand Scenic"},
                    { 111L, "Kadjar"},
                    { 112L, "Kangoo"},
                    { 113L, "Kangoo Express"},
                    { 114L, "Koleos"},
                    { 115L, "Laguna"},
                    { 116L, "Laguna Grandtour"},
                    { 117L, "Latitude"},
                    { 118L, "Mascott"},
                    { 119L, "Mégane"},
                    { 120L, "Mégane CC"},
                    { 121L, "Mégane Combi"},
                    { 122L, "Mégane Grandtour"},
                    { 123L, "Mégane Coupé"},
                    { 124L, "Mégane Scénic"},
                    { 125L, "Scénic"},
                    { 126L, "Talisman"},
                    { 127L, "Talisman Grandtour"},
                    { 128L, "Thalia"},
                    { 129L, "Twingo"},
                    { 130L, "Wind"},
                    { 131L, "Zoé"},
                    { 132L, "1007"},
                    { 133L, "107"},
                    { 134L, "106"},
                    { 135L, "108"},
                    { 136L, "2008"},
                    { 137L, "205"},
                    { 138L, "205 Cabrio"},
                    { 139L, "206"},
                    { 140L, "206 CC"},
                    { 141L, "206 SW"},
                    { 142L, "207"},
                    { 143L, "207 CC"},
                    { 144L, "207 SW"},
                    { 145L, "306"},
                    { 146L, "307"},
                    { 147L, "307 CC"},
                    { 148L, "307 SW"},
                    { 149L, "308"},
                    { 150L, "308 CC"},
                    { 151L, "308 SW"},
                    { 152L, "309"},
                    { 153L, "4007"},
                    { 154L, "4008"},
                    { 155L, "405"},
                    { 156L, "406"},
                    { 157L, "407"},
                    { 158L, "407 SW"},
                    { 159L, "5008"},
                    { 160L, "508"},
                    { 161L, "508 SW"},
                    { 162L, "605"},
                    { 163L, "806"},
                    { 164L, "607"},
                    { 165L, "807"},
                    { 166L, "Bipper"},
                    { 167L, "RCZ Dokker"},
                    { 168L, "Duster"},
                    { 169L, "Lodgy"},
                    { 170L, "Logan"},
                    { 171L, "Logan MCV"},
                    { 172L, "Logan Van"},
                    { 173L, "Sandero"},
                    { 174L, "Solenza Berlingo"},
                    { 175L, "C-Crosser"},
                    { 176L, "C-Elissée"},
                    { 177L, "C-Zero"},
                    { 178L, "C1"},
                    { 179L, "C2"},
                    { 180L, "C3"},
                    { 181L, "C3 Picasso"},
                    { 182L, "C4"},
                    { 183L, "C4 Aircross"},
                    { 184L, "C4 Cactus"},
                    { 185L, "C4 Coupé"},
                    { 186L, "C4 Grand Picasso"},
                    { 187L, "C4 Sedan"},
                    { 188L, "C5"},
                    { 189L, "C5 Break"},
                    { 190L, "C5 Tourer"},
                    { 191L, "C6"},
                    { 192L, "C8"},
                    { 193L, "DS3"},
                    { 194L, "DS4"},
                    { 195L, "DS5"},
                    { 196L, "Evasion"},
                    { 197L, "Jumper"},
                    { 198L, "Jumpy"},
                    { 199L, "Saxo"},
                    { 200L, "Nemo"},
                    { 201L, "Xantia"},
                    { 202L, "Xsara Agila"},
                    { 203L, "Ampera"},
                    { 204L, "Antara"},
                    { 205L, "Astra"},
                    { 206L, "Astra cabrio"},
                    { 207L, "Astra caravan"},
                    { 208L, "Astra coupé"},
                    { 209L, "Calibra"},
                    { 210L, "Campo"},
                    { 211L, "Cascada"},
                    { 212L, "Corsa"},
                    { 213L, "Frontera"},
                    { 214L, "Insignia"},
                    { 215L, "Insignia kombi"},
                    { 216L, "Kadett"},
                    { 217L, "Meriva"},
                    { 218L, "Mokka"},
                    { 219L, "Movano"},
                    { 220L, "Omega"},
                    { 221L, "Signum"},
                    { 222L, "Vectra"},
                    { 223L, "Vectra Caravan"},
                    { 224L, "Vivaro"},
                    { 225L, "Vivaro Kombi"},
                    { 226L, "Zafira"},
                    { 227L, "Favorit"},
                    { 228L, "Felicia"},
                    { 229L, "Citigo"},
                    { 230L, "Fabia"},
                    { 231L, "Fabia Combi"},
                    { 232L, "Fabia Sedan"},
                    { 233L, "Felicia Combi"},
                    { 234L, "Octavia"},
                    { 235L, "Octavia Combi"},
                    { 236L, "Roomster"},
                    { 237L, "Yeti"},
                    { 238L, "Rapid"},
                    { 239L, "Rapid Spaceback"},
                    { 240L, "Superb"},
                    { 241L, "Superb Combi"},
                    { 242L, "Alero"},
                    { 243L, "Aveo"},
                    { 244L, "Camaro"},
                    { 245L, "Captiva"},
                    { 246L, "Corvette"},
                    { 247L, "Cruze"},
                    { 248L, "Cruze SW"},
                    { 249L, "Epica"},
                    { 250L, "Equinox"},
                    { 251L, "Evanda"},
                    { 252L, "HHR"},
                    { 253L, "Kalos"},
                    { 254L, "Lacetti"},
                    { 255L, "Lacetti SW"},
                    { 256L, "Lumina"},
                    { 257L, "Malibu"},
                    { 258L, "Matiz"},
                    { 259L, "Monte Carlo"},
                    { 260L, "Nubira"},
                    { 261L, "Orlando"},
                    { 262L, "Spark"},
                    { 263L, "Suburban"},
                    { 264L, "Tacuma"},
                    { 265L, "Tahoe"},
                    { 266L, "Trax"},
                    { 267L, "911 Carrera"},
                    { 268L, "911 Carrera Cabrio"},
                    { 269L, "911 Targa"},
                    { 270L, "911 Turbo"},
                    { 271L, "924"},
                    { 272L, "944"},
                    { 273L, "997"},
                    { 274L, "Boxster"},
                    { 275L, "Cayenne"},
                    { 276L, "Cayman"},
                    { 277L, "Macan"},
                    { 278L, "Panamera"},
                    { 279L, "Accord"},
                    { 280L, "Accord Coupé"},
                    { 281L, "Accord Tourer"},
                    { 282L, "City"},
                    { 283L, "Civic"},
                    { 284L, "Civic Aerodeck"},
                    { 285L, "Civic Coupé"},
                    { 286L, "Civic Tourer"},
                    { 287L, "Civic Type R"},
                    { 288L, "CR-V"},
                    { 289L, "CR-X"},
                    { 290L, "CR-Z"},
                    { 291L, "FR-V"},
                    { 292L, "HR-V"},
                    { 293L, "Insight"},
                    { 294L, "Integra"},
                    { 295L, "Jazz"},
                    { 296L, "Legend"},
                    { 297L, "Prelude"},
                    { 298L, "BRZ"},
                    { 299L, "Forester"},
                    { 300L, "Impreza"},
                    { 301L, "Impreza Wagon"},
                    { 302L, "Justy"},
                    { 303L, "Legacy"},
                    { 304L, "Legacy Wagon"},
                    { 305L, "Legacy Outback"},
                    { 306L, "Levorg"},
                    { 307L, "Outback"},
                    { 308L, "SVX"},
                    { 309L, "Tribeca"},
                    { 310L, "Tribeca B9"},
                    { 311L, "XV"},
                    { 312L, "121"},
                    { 313L, "2"},
                    { 314L, "3"},
                    { 315L, "323"},
                    { 316L, "323 Combi"},
                    { 317L, "323 Coupé"},
                    { 318L, "323 F"},
                    { 319L, "5"},
                    { 320L, "6"},
                    { 321L, "6 Combi"},
                    { 322L, "626"},
                    { 323L, "626 Combi"},
                    { 324L, "B-Fighter"},
                    { 325L, "B2500"},
                    { 326L, "BT"},
                    { 327L, "CX-3"},
                    { 328L, "CX-5"},
                    { 329L, "CX-7"},
                    { 330L, "CX-9"},
                    { 331L, "Demio"},
                    { 332L, "MPV"},
                    { 333L, "MX-3"},
                    { 334L, "MX-5"},
                    { 335L, "MX-6"},
                    { 336L, "Premacy"},
                    { 337L, "RX-7"},
                    { 338L, "RX-8"},
                    { 339L, "Xedox 6"},
                    { 340L, "3000 GT"},
                    { 341L, "ASX"},
                    { 342L, "Carisma"},
                    { 343L, "Colt"},
                    { 344L, "Colt CC"},
                    { 345L, "Eclipse"},
                    { 346L, "Fuso canter"},
                    { 347L, "Galant"},
                    { 348L, "Galant Combi"},
                    { 349L, "Grandis"},
                    { 350L, "L200"},
                    { 351L, "L200 Pick up"},
                    { 352L, "L200 Pick up Allrad"},
                    { 353L, "L300"},
                    { 354L, "Lancer"},
                    { 355L, "Lancer Combi"},
                    { 356L, "Lancer Evo"},
                    { 357L, "Lancer Sportback"},
                    { 358L, "Outlander"},
                    { 359L, "Pajero"},
                    { 360L, "Pajeto Pinin"},
                    { 361L, "Pajero Pinin Wagon"},
                    { 362L, "Pajero Sport"},
                    { 363L, "Pajero Wagon"},
                    { 364L, "Space Star"},
                    { 365L, "CT"},
                    { 366L, "GS"},
                    { 367L, "GS 300"},
                    { 368L, "GX"},
                    { 369L, "IS"},
                    { 370L, "IS 200"},
                    { 371L, "IS 250 C"},
                    { 372L, "IS-F"},
                    { 373L, "LS"},
                    { 374L, "LX"},
                    { 375L, "NX"},
                    { 376L, "RC F"},
                    { 377L, "RX"},
                    { 378L, "RX 300"},
                    { 379L, "RX 400h"},
                    { 380L, "RX 450h"},
                    { 381L, "SC 430"},
                    { 382L, "i3"},
                    { 383L, "i8"},
                    { 384L, "M3"},
                    { 385L, "M4"},
                    { 386L, "M5"},
                    { 387L, "M6"},
                    { 388L, "Rad 1"},
                    { 389L, "Rad 1 Cabrio"},
                    { 390L, "Rad 1 Coupé"},
                    { 391L, "Rad 2"},
                    { 392L, "Rad 2 Active Tourer"},
                    { 393L, "Rad 2 Coupé"},
                    { 394L, "Rad 2 Gran Tourer"},
                    { 395L, "Rad 3"},
                    { 396L, "Rad 3 Cabrio"},
                    { 397L, "Rad 3 Compact"},
                    { 398L, "Rad 3 Coupé"},
                    { 399L, "Rad 3 GT"},
                    { 400L, "Rad 3 Touring"},
                    { 401L, "Rad 4"},
                    { 402L, "Rad 4 Cabrio"},
                    { 403L, "Rad 4 Gran Coupé"},
                    { 404L, "Rad 5"},
                    { 405L, "Rad 5 GT"},
                    { 406L, "Rad 5 Touring"},
                    { 407L, "Rad 6"},
                    { 408L, "Rad 6 Cabrio"},
                    { 409L, "Rad 6 Coupé"},
                    { 410L, "Rad 6 Gran Coupé"},
                    { 411L, "Rad 7"},
                    { 412L, "Rad 8 Coupé"},
                    { 413L, "X1"},
                    { 414L, "X3"},
                    { 415L, "X4"},
                    { 416L, "X5"},
                    { 417L, "X6"},
                    { 418L, "Z3"},
                    { 419L, "Z3 Coupé"},
                    { 420L, "Z3 Roadster"},
                    { 421L, "Z4"},
                    { 422L, "Z4 Roadster"},
                    { 423L, "Amarok"},
                    { 424L, "Beetle"},
                    { 425L, "Bora"},
                    { 426L, "Bora Variant"},
                    { 427L, "Caddy"},
                    { 428L, "Caddy Van"},
                    { 429L, "Life"},
                    { 430L, "California"},
                    { 431L, "Caravelle"},
                    { 432L, "CC"},
                    { 433L, "Crafter"},
                    { 434L, "Crafter Van"},
                    { 435L, "Crafter Kombi"},
                    { 436L, "CrossTouran"},
                    { 437L, "Eos"},
                    { 438L, "Fox"},
                    { 439L, "Golf"},
                    { 440L, "Golf Cabrio"},
                    { 441L, "Golf Plus"},
                    { 442L, "Golf Sportvan"},
                    { 443L, "Golf Variant"},
                    { 444L, "Jetta"},
                    { 445L, "LT"},
                    { 446L, "Lupo"},
                    { 447L, "Multivan"},
                    { 448L, "New Beetle"},
                    { 449L, "New Beetle Cabrio"},
                    { 450L, "Passat"},
                    { 451L, "Passat Alltrack"},
                    { 452L, "Passat CC"},
                    { 453L, "Passat Variant"},
                    { 454L, "Passat Variant Van"},
                    { 455L, "Phaeton"},
                    { 456L, "Polo"},
                    { 457L, "Polo Van"},
                    { 458L, "Polo Variant"},
                    { 459L, "Scirocco"},
                    { 460L, "Sharan"},
                    { 461L, "T4"},
                    { 462L, "T4 Caravelle"},
                    { 463L, "T4 Multivan"},
                    { 464L, "T5"},
                    { 465L, "T5 Caravelle"},
                    { 466L, "T5 Multivan"},
                    { 467L, "T5 Transporter Shuttle"},
                    { 468L, "Tiguan"},
                    { 469L, "Touareg"},
                    { 470L, "Touran"},
                    { 471L, "Alto"},
                    { 472L, "Baleno"},
                    { 473L, "Baleno kombi"},
                    { 474L, "Grand Vitara"},
                    { 475L, "Grand Vitara XL-7"},
                    { 476L, "Ignis"},
                    { 477L, "Jimny"},
                    { 478L, "Kizashi"},
                    { 479L, "Liana"},
                    { 480L, "Samurai"},
                    { 481L, "Splash"},
                    { 482L, "Swift"},
                    { 483L, "SX4"},
                    { 484L, "SX4 Sedan"},
                    { 485L, "Vitara"},
                    { 486L, "Wagon R+"},
                    { 487L, "100 D"},
                    { 488L, "115"},
                    { 489L, "124"},
                    { 490L, "126"},
                    { 491L, "190"},
                    { 492L, "190 D"},
                    { 493L, "190 E"},
                    { 494L, "200 - 300"},
                    { 495L, "200 D"},
                    { 496L, "200 E"},
                    { 497L, "210 Van"},
                    { 498L, "210 kombi"},
                    { 499L, "310 Van"},
                    { 500L, "310 kombi"},
                    { 501L, "230 - 300 CE Coupé"},
                    { 502L, "260 - 560 SE"},
                    { 503L, "260 - 560 SEL"},
                    { 504L, "500 - 600 SEC Coupé"},
                    { 505L, "Trieda A"},
                    { 506L, "A"},
                    { 507L, "A L"},
                    { 508L, "AMG GT"},
                    { 509L, "Trieda B"},
                    { 510L, "Trieda C"},
                    { 511L, "C"},
                    { 512L, "C Sportcoupé"},
                    { 513L, "C T"},
                    { 514L, "Citan"},
                    { 515L, "CL"},
                    { 516L, "CL"},
                    { 517L, "CLA"},
                    { 518L, "CLC"},
                    { 519L, "CLK Cabrio"},
                    { 520L, "CLK Coupé"},
                    { 521L, "CLS"},
                    { 522L, "Trieda E"},
                    { 523L, "E"},
                    { 524L, "E Cabrio"},
                    { 525L, "E Coupé"},
                    { 526L, "E T"},
                    { 527L, "Trieda G"},
                    { 528L, "G Cabrio"},
                    { 529L, "GL"},
                    { 530L, "GLA"},
                    { 531L, "GLC"},
                    { 532L, "GLE"},
                    { 533L, "GLK"},
                    { 534L, "Trieda M"},
                    { 535L, "MB 100"},
                    { 536L, "Trieda R"},
                    { 537L, "Trieda S"},
                    { 538L, "S"},
                    { 539L, "S Coupé"},
                    { 540L, "SL"},
                    { 541L, "SLC"},
                    { 542L, "SLK"},
                    { 543L, "SLR"},
                    { 544L, "Sprinter"},
                    { 545L, "44994"},
                    { 546L, "9-3 Cabriolet"},
                    { 547L, "9-3 Coupé"},
                    { 548L, "9-3 SportCombi"},
                    { 549L, "45055"},
                    { 550L, "9-5 SportCombi"},
                    { 551L, "900"},
                    { 552L, "900 C"},
                    { 553L, "900 C Turbo"},
                    { 554L, "9000"},
                    { 555L, "100"},
                    { 556L, "100 Avant"},
                    { 557L, "80"},
                    { 558L, "80 Avant"},
                    { 559L, "80 Cabrio"},
                    { 560L, "90"},
                    { 561L, "A1"},
                    { 562L, "A2"},
                    { 563L, "A3"},
                    { 564L, "A3 Cabriolet"},
                    { 565L, "A3 Limuzina"},
                    { 566L, "A3 Sportback"},
                    { 567L, "A4"},
                    { 568L, "A4 Allroad"},
                    { 569L, "A4 Avant"},
                    { 570L, "A4 Cabriolet"},
                    { 571L, "A5"},
                    { 572L, "A5 Cabriolet"},
                    { 573L, "A5 Sportback"},
                    { 574L, "A6"},
                    { 575L, "A6 Allroad"},
                    { 576L, "A6 Avant"},
                    { 577L, "A7"},
                    { 578L, "A8"},
                    { 579L, "A8 Long"},
                    { 580L, "Q3"},
                    { 581L, "Q5"},
                    { 582L, "Q7"},
                    { 583L, "R8"},
                    { 584L, "RS4 Cabriolet"},
                    { 585L, "RS4/RS4 Avant"},
                    { 586L, "RS5"},
                    { 587L, "RS6 Avant"},
                    { 588L, "RS7"},
                    { 589L, "S3/S3 Sportback"},
                    { 590L, "S4 Cabriolet"},
                    { 591L, "S4/S4 Avant"},
                    { 592L, "S5/S5 Cabriolet"},
                    { 593L, "S6/RS6"},
                    { 594L, "S7"},
                    { 595L, "S8"},
                    { 596L, "SQ5"},
                    { 597L, "TT Coupé"},
                    { 598L, "TT Roadster"},
                    { 599L, "TTS"},
                    { 600L, "Avella"},
                    { 601L, "Besta"},
                    { 602L, "Carens"},
                    { 603L, "Carnival"},
                    { 604L, "Cee`d"},
                    { 605L, "Cee`d SW"},
                    { 606L, "Cerato"},
                    { 607L, "K 2500"},
                    { 608L, "Magentis"},
                    { 609L, "Opirus"},
                    { 610L, "Optima"},
                    { 611L, "Picanto"},
                    { 612L, "Pregio"},
                    { 613L, "Pride"},
                    { 614L, "Pro Cee`d"},
                    { 615L, "Rio"},
                    { 616L, "Rio Combi"},
                    { 617L, "Rio sedan"},
                    { 618L, "Sephia"},
                    { 619L, "Shuma"},
                    { 620L, "Sorento"},
                    { 621L, "Soul"},
                    { 622L, "Sportage"},
                    { 623L, "Venga"},
                    { 624L, "109"},
                    { 625L, "Defender"},
                    { 626L, "Discovery"},
                    { 627L, "Discovery Sport"},
                    { 628L, "Freelander"},
                    { 629L, "Range Rover"},
                    { 630L, "Range Rover Evoque"},
                    { 631L, "Range Rover Sport"},
                    { 632L, "Avenger"},
                    { 633L, "Caliber"},
                    { 634L, "Challenger"},
                    { 635L, "Charger"},
                    { 636L, "Grand Caravan"},
                    { 637L, "Journey"},
                    { 638L, "Magnum"},
                    { 639L, "Nitro"},
                    { 640L, "RAM"},
                    { 641L, "Stealth"},
                    { 642L, "Viper"},
                    { 643L, "300 C"},
                    { 644L, "300 C Touring"},
                    { 645L, "300 M"},
                    { 646L, "Crossfire"},
                    { 647L, "Grand Voyager"},
                    { 648L, "LHS"},
                    { 649L, "Neon"},
                    { 650L, "Pacifica"},
                    { 651L, "Plymouth"},
                    { 652L, "PT Cruiser"},
                    { 653L, "Sebring"},
                    { 654L, "Sebring Convertible"},
                    { 655L, "Stratus"},
                    { 656L, "Stratus Cabrio"},
                    { 657L, "Town & Country"},
                    { 658L, "Voyager"},
                    { 659L, "Aerostar"},
                    { 660L, "B-Max"},
                    { 661L, "C-Max"},
                    { 662L, "Cortina"},
                    { 663L, "Cougar"},
                    { 664L, "Edge"},
                    { 665L, "Escort"},
                    { 666L, "Escort Cabrio"},
                    { 667L, "Escort kombi"},
                    { 668L, "Explorer"},
                    { 669L, "F-150"},
                    { 670L, "F-250"},
                    { 671L, "Fiesta"},
                    { 672L, "Focus"},
                    { 673L, "Focus C-Max"},
                    { 674L, "Focus CC"},
                    { 675L, "Focus kombi"},
                    { 676L, "Fusion"},
                    { 677L, "Galaxy"},
                    { 678L, "Grand C-Max"},
                    { 679L, "Ka"},
                    { 680L, "Kuga"},
                    { 681L, "Maverick"},
                    { 682L, "Mondeo"},
                    { 683L, "Mondeo Combi"},
                    { 684L, "Mustang"},
                    { 685L, "Orion"},
                    { 686L, "Puma"},
                    { 687L, "Ranger"},
                    { 688L, "S-Max"},
                    { 689L, "Sierra"},
                    { 690L, "Street Ka"},
                    { 691L, "Tourneo Connect"},
                    { 692L, "Tourneo Custom"},
                    { 693L, "Transit"},
                    { 694L, "Transit"},
                    { 695L, "Transit Bus"},
                    { 696L, "Transit Connect LWB"},
                    { 697L, "Transit Courier"},
                    { 698L, "Transit Custom"},
                    { 699L, "Transit kombi"},
                    { 700L, "Transit Tourneo"},
                    { 701L, "Transit Valnik"},
                    { 702L, "Transit Van"},
                    { 703L, "Transit Van 350"},
                    { 704L, "Windstar"},
                    { 705L, "H2"},
                    { 706L, "H3"},
                    { 707L, "EX"},
                    { 708L, "FX"},
                    { 709L, "G"},
                    { 710L, "G Coupé"},
                    { 711L, "M"},
                    { 712L, "Q"},
                    { 713L, "QX"},
                    { 714L, "Daimler"},
                    { 715L, "F-Pace"},
                    { 716L, "F-Type"},
                    { 717L, "S-Type"},
                    { 718L, "Sovereign"},
                    { 719L, "X-Type"},
                    { 720L, "X-type Estate"},
                    { 721L, "XE"},
                    { 722L, "XF"},
                    { 723L, "XJ"},
                    { 724L, "XJ12"},
                    { 725L, "XJ6"},
                    { 726L, "XJ8"},
                    { 727L, "XJ8"},
                    { 728L, "XJR"},
                    { 729L, "XK"},
                    { 730L, "XK8 Convertible"},
                    { 731L, "XKR"},
                    { 732L, "XKR Convertible"},
                    { 733L, "Cherokee"},
                    { 734L, "Commander"},
                    { 735L, "Compass"},
                    { 736L, "Grand Cherokee"},
                    { 737L, "Patriot"},
                    { 738L, "Renegade"},
                    { 739L, "Wrangler"},
                    { 740L, "100 NX"},
                    { 741L, "200 SX"},
                    { 742L, "350 Z"},
                    { 743L, "350 Z Roadster"},
                    { 744L, "370 Z"},
                    { 745L, "Almera"},
                    { 746L, "Almera Tino"},
                    { 747L, "Cabstar E - T"},
                    { 748L, "Cabstar TL2 Valnik"},
                    { 749L, "e-NV200"},
                    { 750L, "GT-R"},
                    { 751L, "Insterstar"},
                    { 752L, "Juke"},
                    { 753L, "King Cab"},
                    { 754L, "Leaf"},
                    { 755L, "Maxima"},
                    { 756L, "Maxima QX"},
                    { 757L, "Micra"},
                    { 758L, "Murano"},
                    { 759L, "Navara"},
                    { 760L, "Note"},
                    { 761L, "NP300 Pickup"},
                    { 762L, "NV200"},
                    { 763L, "NV400"},
                    { 764L, "Pathfinder"},
                    { 765L, "Patrol"},
                    { 766L, "Patrol GR"},
                    { 767L, "Pickup"},
                    { 768L, "Pixo"},
                    { 769L, "Primastar"},
                    { 770L, "Primastar Combi"},
                    { 771L, "Primera"},
                    { 772L, "Primera Combi"},
                    { 773L, "Pulsar"},
                    { 774L, "Qashqai"},
                    { 775L, "Serena"},
                    { 776L, "Sunny"},
                    { 777L, "Terrano"},
                    { 778L, "Tiida"},
                    { 779L, "Trade"},
                    { 780L, "Vanette Cargo"},
                    { 781L, "X-Trail"},
                    { 782L, "240"},
                    { 783L, "340"},
                    { 784L, "360"},
                    { 785L, "460"},
                    { 786L, "850"},
                    { 787L, "850 kombi"},
                    { 788L, "C30"},
                    { 789L, "C70"},
                    { 790L, "C70 Cabrio"},
                    { 791L, "C70 Coupé"},
                    { 792L, "S40"},
                    { 793L, "S60"},
                    { 794L, "S70"},
                    { 795L, "S80"},
                    { 796L, "S90"},
                    { 797L, "V40"},
                    { 798L, "V50"},
                    { 799L, "V60"},
                    { 800L, "V70"},
                    { 801L, "V90"},
                    { 802L, "XC60"},
                    { 803L, "XC70"},
                    { 804L, "XC90"},
                    { 805L, "Espero"},
                    { 806L, "Kalos"},
                    { 807L, "Lacetti"},
                    { 808L, "Lanos"},
                    { 809L, "Leganza"},
                    { 810L, "Lublin"},
                    { 811L, "Matiz"},
                    { 812L, "Nexia"},
                    { 813L, "Nubira"},
                    { 814L, "Nubira kombi"},
                    { 815L, "Racer"},
                    { 816L, "Tacuma"},
                    { 817L, "Tico"},
                    { 818L, "1100"},
                    { 819L, "126"},
                    { 820L, "500"},
                    { 821L, "500L"},
                    { 822L, "500X"},
                    { 823L, "850"},
                    { 824L, "Barchetta"},
                    { 825L, "Brava"},
                    { 826L, "Cinquecento"},
                    { 827L, "Coupé"},
                    { 828L, "Croma"},
                    { 829L, "Doblo"},
                    { 830L, "Doblo Cargo"},
                    { 831L, "Doblo Cargo Combi"},
                    { 832L, "Ducato"},
                    { 833L, "Ducato Van"},
                    { 834L, "Ducato Kombi"},
                    { 835L, "Ducato Podvozok"},
                    { 836L, "Florino"},
                    { 837L, "Florino Combi"},
                    { 838L, "Freemont"},
                    { 839L, "Grande Punto"},
                    { 840L, "Idea"},
                    { 841L, "Linea"},
                    { 842L, "Marea"},
                    { 843L, "Marea Weekend"},
                    { 844L, "Multipla"},
                    { 845L, "Palio Weekend"},
                    { 846L, "Panda"},
                    { 847L, "Panda Van"},
                    { 848L, "Punto"},
                    { 849L, "Punto Cabriolet"},
                    { 850L, "Punto Evo"},
                    { 851L, "Punto Van"},
                    { 852L, "Qubo"},
                    { 853L, "Scudo"},
                    { 854L, "Scudo Van"},
                    { 855L, "Scudo Kombi"},
                    { 856L, "Sedici"},
                    { 857L, "Seicento"},
                    { 858L, "Stilo"},
                    { 859L, "Stilo Multiwagon"},
                    { 860L, "Strada"},
                    { 861L, "Talento"},
                    { 862L, "Tipo"},
                    { 863L, "Ulysse"},
                    { 864L, "Uno"},
                    { 865L, "X1/9"},
                    { 866L, "Cooper"},
                    { 867L, "Cooper Cabrio"},
                    { 868L, "Cooper Clubman"},
                    { 869L, "Cooper D"},
                    { 870L, "Cooper D Clubman"},
                    { 871L, "Cooper S"},
                    { 872L, "Cooper S Cabrio"},
                    { 873L, "Cooper S Clubman"},
                    { 874L, "Countryman"},
                    { 875L, "Mini One"},
                    { 876L, "One D"},
                    { 877L, "200"},
                    { 878L, "214"},
                    { 879L, "218"},
                    { 880L, "25"},
                    { 881L, "400"},
                    { 882L, "414"},
                    { 883L, "416"},
                    { 884L, "620"},
                    { 885L, "75"},
                    { 886L, "Cabrio"},
                    { 887L, "City-Coupé"},
                    { 888L, "Compact Pulse"},
                    { 889L, "Forfour"},
                    { 890L, "Fortwo cabrio"},
                    { 891L, "Fortwo coupé"},
                    { 892L, "Roadster"},


                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "ID", "CreationDate", "Email", "EnableAccess", "LastLoginDate", "ModifiedDate", "Name", "Password", "Surname", "UserType", "GarageID" },
                values: new object[,]
                {
                    { 1L, new DateTime(2021, 1, 25, 10, 04, 5, 768, DateTimeKind.Local).AddTicks(127), "atselios@classter.com", 1, new DateTime(2023, 1, 27, 15, 37, 7, 125, DateTimeKind.Local).AddTicks(342), null, "Alexandros", "1", "Tselios",(long)Enum.EnableAccess.Enable,1L },
                    { 2L, new DateTime(2021, 1, 26, 12, 46, 7, 456, DateTimeKind.Local).AddTicks(144), "efi.vanni@gmail.com", 1, new DateTime(2022, 11, 15, 13, 26, 8, 256, DateTimeKind.Local).AddTicks(699), null, "Efthumia", "f1234!", "Varvagianni", (long)Enum.EnableAccess.Enable,1L },
                    { 3L, new DateTime(2022, 9, 30, 16, 56, 3, 125, DateTimeKind.Local).AddTicks(156), "kkitsikou@hotmail.com", 1, new DateTime(2022, 7, 9, 12, 05, 4, 368, DateTimeKind.Local).AddTicks(456), null, "Kostas", "gafa#$#", "Kitsikou", (long)Enum.EnableAccess.Enable,2L },
                    { 4L, new DateTime(2022, 12, 16, 20, 00, 1, 929, DateTimeKind.Local).AddTicks(169), "mpapadopoulos@yahoo.gr", 1, new DateTime(2022, 6, 4, 22, 00, 1, 789, DateTimeKind.Local).AddTicks(768), null, "Marios", "DfG34#$%^", "Papadopoulos", (long)Enum.EnableAccess.Disable, 3L }
                });

            migrationBuilder.InsertData(
                table: "CarModelManufacturerYear",
                columns: new[] { "ID", "CarManufacturerID", "CarModelID", "CarModelYearID" },
                values: new object[,]
                {
                    { 1L, 2L, 52L, 66L },
                    { 2L, 24L, 2L, 62L },
                    { 3L, 62L, 85L, 69L },
                    { 4L, 24L, 15L, 61L },
                    { 5L, 24L, 16L, 62L },
                    { 6L, 24L, 17L, 63L }
                });

            migrationBuilder.InsertData(
                table: "UserModels",
                columns: new[] { "ID", "UserID", "ModelManufacturerYearID", "ModelYearID", "LicencePlate", "VIN", "Color", "Kilometer" },
                values: new object[,]
                {
                    {1L, 1L, 1L, 66L, "KBT5670", "ZAR94000007368150", 101, 156125},
                    {2L, 1L, 3L, 67L, "EYB7174", "VNKKG3D330A048555", 142, 27450},
                    {3L, 1L, 4L, 67L, "NIZ2654", "NLHBA51BABZ014926", 4, 88956},
                    {4L, 2L, 5L, 68L, "XEZ6532", "KHX94000007259841", 5, 220653},
                    {5L, 2L, 6L, 72L, "KBH1452", "JNKCV61E09M303716", 6, 65402},
                    {6L, 3L, 6L, 73L, "AHZ1495", "JH4DA9460MS032070", 6, 9563}
                });

            var GetCustomerCars = @"CREATE PROCEDURE GetCustomerCars
                    -- Add the parameters for the stored procedure here
                    @UserID BIGINT
                    AS
                        BEGIN
                            SET NOCOUNT ON;
		                    SELECT UM.ID, 
			                       UM.UserID, 
			                       CMAN.ManufacturerName, 
			                       CM.ModelName, 
			                       CMY.Description AS ModelYear, 
			                       UM.LicencePlate, 
			                       UM.VIN, 
			                       UM.Color, 
			                       UM.Kilometer
		                    FROM UserModels UM
			                     INNER JOIN CarModelManufacturerYear CMMY ON CMMY.ID = um.ModelManufacturerYearID
			                     INNER JOIN CarModels CM ON CM.ID = CMMY.CarModelID
			                     INNER JOIN CarManufacturer CMAN ON CMAN.ID = CMMY.CarManufacturerID
			                     INNER JOIN CarModelYear CMY ON CMY.ID = CMMY.CarModelYearID
		                    WHERE UserId = @UserID;
                        END";

            migrationBuilder.Sql(GetCustomerCars);

            var GetCustomerCar = @"CREATE PROCEDURE GetCustomerCar
                    -- Add the parameters for the stored procedure here
                    @UserModelID BIGINT
                    AS
                        BEGIN
                            SET NOCOUNT ON;
                            SELECT UM.ID, 
                                   UM.UserID, 
                                   CMAN.ManufacturerName, 
                                   CM.ModelName, 
			                       CMY.Description AS ModelYear, 
                                   UM.LicencePlate, 
                                   UM.VIN, 
                                   UM.Color, 
                                   UM.Kilometer
                            FROM UserModels UM
                                 INNER JOIN CarModelManufacturerYear CMMY ON CMMY.ID = um.ModelManufacturerYearID
                                 INNER JOIN CarModels CM ON CM.ID = CMMY.CarModelID
                                 INNER JOIN CarManufacturer CMAN ON CMAN.ID = CMMY.CarManufacturerID
			                     INNER JOIN CarModelYear CMY ON CMY.ID = CMMY.CarModelYearID
                            WHERE UM.ID = @UserModelID;
                        END";

            migrationBuilder.Sql(GetCustomerCar);

            migrationBuilder.CreateIndex(
                name: "IX_CarModelManufacturerYear_CarManufacturerID",
                table: "CarModelManufacturerYear",
                column: "CarManufacturerID");

            migrationBuilder.CreateIndex(
                name: "IX_CarModelManufacturerYear_CarModelID",
                table: "CarModelManufacturerYear",
                column: "CarModelID");

            migrationBuilder.CreateIndex(
                name: "IX_CarModelManufacturerYear_CarModelYearID",
                table: "CarModelManufacturerYear",
                column: "CarModelYearID");

            migrationBuilder.CreateIndex(
                name: "IX_UserModels_ModelManufacturerYearID",
                table: "UserModels",
                column: "ModelManufacturerYearID");

            migrationBuilder.CreateIndex(
                name: "IX_UserModels_ModelYearID",
                table: "UserModels",
                column: "ModelYearID");

            migrationBuilder.CreateIndex(
                name: "IX_UserModels_UserID",
                table: "UserModels",
                column: "UserID");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "UserModels");

            migrationBuilder.DropTable(
                name: "CarModelManufacturerYear");

            migrationBuilder.DropTable(
                name: "Users");

            migrationBuilder.DropTable(
                name: "CarManufacturer");

            migrationBuilder.DropTable(
                name: "CarModelYear");

            migrationBuilder.DropTable(
                name: "CarModels");
        }
    }
}
